### ISSUE TITLE
SimpleStepExecutionSplitter split method not working on job restart [BATCH-2499]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#1104]
**[Dhruv Patel](https://jira.spring.io/secure/ViewProfile.jspa?name=dhruv.patel20@gmail.com)** opened **[BATCH-2499](https://jira.spring.io/browse/BATCH-2499?redirect=false)** and commented

On a job restart (via the JobOperator), the SimpleStepExecutionSplitter's split method is falling over on on line 207:
int splitSize = (int) context.getLong(key, gridSize);

This is because the gridSize stored in the ExecutionContext is an integer rather than a long. So there is a ClassCastException in ExecutionContext (line 281). As we are restarting an existing JobExecution, it is using the stored parameters in the STEP_EXECUTION_CONTEXT database table in the SHORT_CONTEXT column eg:
{"SimpleStepExecutionSplitter.GRID_SIZE":4,"batch.stepType":"org.springframework.batch.core.partition.support.PartitionStep"}

When it is loading the existing StepExecution - it is loading it as an int rather than a long - hence why the SimpleStepExecutionSplitter is breaking.

---

**Affects:** 3.0.6

4 votes, 4 watchers

**Comment by afsarali273** [comment]
Any update on this ? am still getting this error:

`java.lang.ClassCastException: Value for key=[SimpleStepExecutionSplitter.GRID_SIZE] is not of type: [class java.lang.Long], it is [(class java.lang.Integer)100]
	at org.springframework.batch.item.ExecutionContext.readAndValidate(ExecutionContext.java:290)
	at org.springframework.batch.item.ExecutionContext.getLong(ExecutionContext.java:189)
	at org.springframework.batch.item.ExecutionContext.getLong(ExecutionContext.java:206)
	at org.springframework.batch.core.partition.support.SimpleStepExecutionSplitter.getContexts(SimpleStepExecutionSplitter.java:211)
	at org.springframework.batch.core.partition.support.SimpleStepExecutionSplitter.split(SimpleStepExecutionSplitter.java:178)
	at org.springframework.batch.core.partition.support.AbstractPartitionHandler.handle(AbstractPartitionHandler.java:59)
	at org.springframework.batch.core.partition.support.PartitionStep.doExecute(PartitionStep.java:106)
	at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:208)
	at org.springframework.batch.core.job.SimpleStepHandler.handleStep(SimpleStepHandler.java:148)
	at org.springframework.batch.core.job.flow.JobFlowExecutor.executeStep(JobFlowExecutor.java:68)
	at org.springframework.batch.core.job.flow.support.state.StepState.handle(StepState.java:68)
	at org.springframework.batch.core.job.flow.support.SimpleFlow.resume(SimpleFlow.java:169)
	at org.springframework.batch.core.job.flow.support.SimpleFlow.start(SimpleFlow.java:144)
	at org.springframework.batch.core.job.flow.FlowJob.doExecute(FlowJob.java:137)
	at org.springframework.batch.core.job.AbstractJob.execute(AbstractJob.java:319)
	at org.springframework.batch.core.launch.support.SimpleJobLauncher$1.run(SimpleJobLauncher.java:147)
	at org.springframework.core.task.SyncTaskExecutor.execute(SyncTaskExecutor.java:50)
	at org.springframework.batch.core.launch.support.SimpleJobLauncher.run(SimpleJobLauncher.java:140)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.batch.core.configuration.annotation.SimpleBatchConfiguration$PassthruAdvice.invoke(SimpleBatchConfiguration.java:127)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy246.run(Unknown Source)
	at org.springframework.batch.core.launch.support.SimpleJobOperator.restart(SimpleJobOperator.java:280)
	at org.springframework.batch.core.launch.support.SimpleJobOperator$$FastClassBySpringCGLIB$$44ee6049.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:687)
	at org.springframework.batch.core.launch.support.SimpleJobOperator$$EnhancerBySpringCGLIB$$fb5a9719.restart(<generated>)
`

currently am using version : spring batch core - 4.2.4 RELEASE

**Comment by benas** [comment]
@afsarali273 Please provide a minimal complete example that reproduces the issue and we will re-open this issue if necessary.
