### ISSUE TITLE
NullPointerException when @EnableBatchProcessing with BatchConfigurer [BATCH-2430]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-batch#1172]
**[Raph C](https://jira.spring.io/secure/ViewProfile.jspa?name=raphc)** opened **[BATCH-2430](https://jira.spring.io/browse/BATCH-2430?redirect=false)** and commented

Hi,

I noticed Spring-batch causes a NullPointerException when I configure my context like this (`@EnableBatchProcessing` and BatchConfigurer)

```
@EnableBatchProcessing
public class ImpFidBatchConfiguration implements BatchConfigurer {
....
}
```

It seems that Spring register a default SimpleBatchConfiguration whereas I set mine by implementing BatchConfigurer.

```
2015-09-03 15:12:21.932 DEBUG [main] ConfigurationClassBeanDefinitionReader - Registered bean definition for imported @Configuration class org.springframework.batch.core.configuration.annotation.ScopeConfiguration 
2015-09-03 15:12:21.934 DEBUG [main] ConfigurationClassBeanDefinitionReader - Registering bean definition for @Bean method org.springframework.batch.core.configuration.annotation.ScopeConfiguration.stepScope() 
2015-09-03 15:12:21.934 DEBUG [main] ConfigurationClassBeanDefinitionReader - Registering bean definition for @Bean method org.springframework.batch.core.configuration.annotation.ScopeConfiguration.jobScope() 
2015-09-03 15:12:21.934 DEBUG [main] ConfigurationClassBeanDefinitionReader - Registered bean definition for imported @Configuration class org.springframework.batch.core.configuration.annotation.SimpleBatchConfiguration 
2015-09-03 15:12:21.934 DEBUG [main] ConfigurationClassBeanDefinitionReader - Registering bean definition for @Bean method org.springframework.batch.core.configuration.annotation.SimpleBatchConfiguration.jobRepository() 
2015-09-03 15:12:21.934 DEBUG [main] ConfigurationClassBeanDefinitionReader - Registering bean definition for @Bean method org.springframework.batch.core.configuration.annotation.SimpleBatchConfiguration.jobLauncher() 
2015-09-03 15:12:21.944 DEBUG [main] ConfigurationClassBeanDefinitionReader - Registering bean definition for @Bean method org.springframework.batch.core.configuration.annotation.SimpleBatchConfiguration.jobRegistry() 
2015-09-03 15:12:21.944 DEBUG [main] ConfigurationClassBeanDefinitionReader - Registering bean definition for @Bean method org.springframework.batch.core.configuration.annotation.SimpleBatchConfiguration.jobExplorer() 
2015-09-03 15:12:21.944 DEBUG [main] ConfigurationClassBeanDefinitionReader - Registering bean definition for @Bean method org.springframework.batch.core.configuration.annotation.SimpleBatchConfiguration.transactionManager() 
2015-09-03 15:12:21.944 DEBUG [main] ConfigurationClassBeanDefinitionReader - Registering bean definition for @Bean method org.springframework.batch.core.configuration.annotation.SimpleBatchConfiguration.jobBuilders() 
2015-09-03 15:12:21.944 DEBUG [main] ConfigurationClassBeanDefinitionReader - Registering bean definition for @Bean method org.springframework.batch.core.configuration.annotation.SimpleBatchConfiguration.stepBuilders() 
2015-09-03 15:12:21.944 DEBUG [main] ConfigurationClassBeanDefinitionReader - Registered bean definition for imported @Configuration class com.bouygtel.inthd.batch.impfid.ImpFidBatchConfiguration 
2015-09-03 15:12:21.954 DEBUG [main] ConfigurationClassBeanDefinitionReader - Registering bean definition for @Bean method com.bouygtel.inthd.batch.impfid.ImpFidBatchConfiguration.prepare() 
2015-09-03 15:12:21.954 DEBUG [main] ConfigurationClassBeanDefinitionReader - Registering bean definition for @Bean method com.bouygtel.inthd.batch.impfid.ImpFidBatchConfiguration.extractArchive() 
2015-09-03 15:12:21.954 DEBUG [main] ConfigurationClassBeanDefinitionReader - Registering bean definition for @Bean method com.bouygtel.inthd.batch.impfid.ImpFidBatchConfiguration.stepScope() 
2015-09-03 15:12:21.954 INFO [main] DefaultListableBeanFactory - Overriding bean definition for bean 'stepScope' with a different definition: replacing [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.batch.core.configuration.annotation.ScopeConfiguration; factoryMethodName=stepScope; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/batch/core/configuration/annotation/ScopeConfiguration.class]] with [Root bean: class [com.bouygtel.inthd.batch.impfid.ImpFidBatchConfiguration]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=stepScope; initMethodName=null; destroyMethodName=(inferred); defined in class com.bouygtel.inthd.batch.impfid.ImpFidBatchConfiguration] 
2015-09-03 15:12:21.954 DEBUG [main] ConfigurationClassBeanDefinitionReader - Registering bean definition for @Bean method com.bouygtel.inthd.batch.impfid.ImpFidBatchConfiguration.jobScope() 
2015-09-03 15:12:21.954 INFO [main] DefaultListableBeanFactory - Overriding bean definition for bean 'jobScope' with a different definition: replacing [Root bean: class [null]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=org.springframework.batch.core.configuration.annotation.ScopeConfiguration; factoryMethodName=jobScope; initMethodName=null; destroyMethodName=(inferred); defined in class path resource [org/springframework/batch/core/configuration/annotation/ScopeConfiguration.class]] with [Root bean: class [com.bouygtel.inthd.batch.impfid.ImpFidBatchConfiguration]; scope=; abstract=false; lazyInit=false; autowireMode=3; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=jobScope; initMethodName=null; destroyMethodName=(inferred); defined in class com.bouygtel.inthd.batch.impfid.ImpFidBatchConfiguration] 
2015-09-03 15:12:21.954 DEBUG [main] ConfigurationClassBeanDefinitionReader - Registering bean definition for @Bean method com.bouygtel.inthd.batch.impfid.ImpFidBatchConfiguration.repositoryFactoryBean() 
2015-09-03 15:12:21.954 DEBUG [main] ConfigurationClassBeanDefinitionReader - Registering bean definition for @Bean method com.bouygtel.inthd.batch.impfid.ImpFidBatchConfiguration.itemFailureLoggerListener() 
2015-09-03 15:12:21.964 DEBUG [main] ConfigurationClassBeanDefinitionReader - Registering bean definition for @Bean method com.bouygtel.inthd.batch.impfid.ImpFidBatchConfiguration.prepareTasklet() 
2015-09-03 15:12:21.964 DEBUG [main] ConfigurationClassBeanDefinitionReader - Registering bean definition for @Bean method com.bouygtel.inthd.batch.impfid.ImpFidBatchConfiguration.getJobExplorer() 
2015-09-03 15:12:21.964 DEBUG [main] ConfigurationClassBeanDefinitionReader - Registering bean definition for @Bean method com.bouygtel.inthd.batch.impfid.ImpFidBatchConfiguration.getJobLauncher() 
2015-09-03 15:12:21.964 DEBUG [main] ConfigurationClassBeanDefinitionReader - Registering bean definition for @Bean method com.bouygtel.inthd.batch.impfid.ImpFidBatchConfiguration.getJobRepository() 
2015-09-03 15:12:21.964 DEBUG [main] ConfigurationClassBeanDefinitionReader - Registering bean definition for @Bean method com.bouygtel.inthd.batch.impfid.ImpFidBatchConfiguration.getTransactionManager() 
```

BTW when I launch a job I get a NullPointerException because the JobRepository used to create the JobExecution instance (the default one) is not the same as this one injected in my flowJob instance (which is my own JobRepository). When the job try to update (AbstractJob.updateStatus) the JobExecution it fails :(

```
2015-09-03 15:12:22.911 ERROR [main] AbstractJob - Encountered fatal error executing job java.lang.NullPointerException: null
	at org.springframework.batch.core.repository.dao.MapJobExecutionDao.synchronizeStatus(MapJobExecutionDao.java:158) ~[spring-batch-core-3.0.2.RELEASE.jar:3.0.2.RELEASE]
	at org.springframework.batch.core.repository.support.SimpleJobRepository.update(SimpleJobRepository.java:161) ~[spring-batch-core-3.0.2.RELEASE.jar:3.0.2.RELEASE]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_40]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_40]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_40]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_40]
```

---

**Affects:** 3.0.2

**Comment by benas** [comment]
> NullPointerException when @EnableBatchProcessing with BatchConfigurer
> Affects: 3.0.2

Spring Batch v3 is not maintained anymore and I'm not able to reproduce this issue with the latest v4.2.1 (and even with v3.0.2 as reported). Here is a quick example:

```java
import org.springframework.batch.core.Job;
import org.springframework.batch.core.JobParameters;
import org.springframework.batch.core.configuration.annotation.DefaultBatchConfigurer;
import org.springframework.batch.core.configuration.annotation.EnableBatchProcessing;
import org.springframework.batch.core.configuration.annotation.JobBuilderFactory;
import org.springframework.batch.core.configuration.annotation.StepBuilderFactory;
import org.springframework.batch.core.launch.JobLauncher;
import org.springframework.batch.repeat.RepeatStatus;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
@EnableBatchProcessing
public class MyJob extends DefaultBatchConfigurer {

	@Bean
	public Job job(JobBuilderFactory jobs, StepBuilderFactory steps) {
		return jobs.get("job")
				.start(steps.get("step")
						.tasklet((contribution, chunkContext) -> {
							System.out.println("hello world");
							return RepeatStatus.FINISHED;
						})
						.build())
				.build();
	}

	public static void main(String[] args) throws Exception {
		ApplicationContext context = new AnnotationConfigApplicationContext(MyJob.class);
		JobLauncher jobLauncher = context.getBean(JobLauncher.class);
		Job job = context.getBean(Job.class);
		jobLauncher.run(job, new JobParameters());
	}

}
```

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.example</groupId>
	<artifactId>demo</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>demo</name>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<java.version>1.8</java.version>
		<spring-batch-core.version>3.0.2.RELEASE</spring-batch-core.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.springframework.batch</groupId>
			<artifactId>spring-batch-core</artifactId>
			<version>${spring-batch-core.version}</version>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<configuration>
					<source>${java.version}</source>
					<target>${java.version}</target>
				</configuration>
			</plugin>
		</plugins>
	</build>

</project>
```

I'm closing this issue as outdated. If you still have the problem, please provide a minimal complete example that reproduces it.
