### ISSUE TITLE
Step-scoped POJO bean can not be referenced by '<tasklet/>' if it has no interface. [BATCH-2259]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#1343]
**[Sanghyuk Jung](https://jira.spring.io/secure/ViewProfile.jspa?name=sanghyuk.jung)** opened **[BATCH-2259](https://jira.spring.io/browse/BATCH-2259?redirect=false)** and commented

POJO beans are automatically wrapped in MethodInvokingTaskletAdapter when the tasklet configuration has  a "method" attribute.

```xml
<batch:job id="simpleTaskJob">
<batch:step id="printStep">
     <batch:tasklet ref="printTask"  method="run"/>
</batch:step>

</batch:job>
```

But a step-scoped bean cannot be referenced by 'ref' and 'method' attributes if it has no interface.

With the following bean definition,

```xml
<bean id="printTask" class="net.benelog.batch.PrintTask" p:message="#{jobParameters['message']}" scope="step"/>
```

```java
public class PrintTask {
    private String message;

    public void setMessage(String message) {
        this.message = message;
    }
    
    public void run(){
        System.out.println(message);
    }
}
```

It throws exceptions as following.

```
Caused by: java.lang.IllegalStateException: target class must declare a method with matching name and parameter types
at org.springframework.util.Assert.state(Assert.java:385)
at org.springframework.batch.item.adapter.AbstractMethodInvokingDelegator.afterPropertiesSet(AbstractMethodInvokingDelegator.java:136)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1612)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1549)
... 46 more
```

I reproduced the problem at  https://github.com/benelog/batch-experiments/blob/master/tasklet-test/src/test/java/net/benelog/batch/SimpleTaskJobTest.java

When the POJO class implements an interface, it has no problem with that usecase.

```java
public class PrintTask implments Runnable {

...
}
```

Or it can be solved by registering MethodInvokingTaskletAdapter directly and removing the 'method' attribute in '\<tasket/>'.

```xml

    <bean id="printTask" class="org.springframework.batch.core.step.tasklet.MethodInvokingTaskletAdapter" p:targetMethod="run" scope="step">
        <property name="targetObject">
            <bean id="printTask" class="net.benelog.batch.PrintTask" p:message="#{jobParameters['message']}"/>
        </property>
    </bean>
```

It may be an trivial problem because the workaround is easy. But it can be more helpful if fixed or documented in future versions.

---

**Affects:** 3.0.0

**Reference URL:** https://github.com/benelog/batch-experiments/blob/master/tasklet-test/src/test/java/net/benelog/batch/SimpleTaskJobTest.java

**Comment by benelog** [comment]
I would like to close this issue since it is no longer relevant.
Although I originally created it in the past, it was migrated from Jira and I don’t have the permission to close it myself, so I’m leaving this comment instead.
