### ISSUE TITLE
Null-pointer exception when using JpaPagingItemReader [BATCH-2256]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#1345]
**[Petar Tahchiev](https://jira.spring.io/secure/ViewProfile.jspa?name=ptahchiev)** opened **[BATCH-2256](https://jira.spring.io/browse/BATCH-2256?redirect=false)** and commented

Hello,

I have this simple reader:

```
    @StepScope
    @Bean(name = {"defaultAbstractEntityReader", "abstractEntityReader"})
    public ItemReader<List<AbstractCatalogableEntityModel>> defaultAbstractEntityReader() {
        final java.util.Map<String, Object> properties = new HashMap<>();
        properties.put("javax.persistence.jdbc.user", configurationService.getConfiguration().getString("db.username"));
        properties.put("javax.persistence.jdbc.password", configurationService.getConfiguration().getString("db.password"));
        properties.put("javax.persistence.jdbc.driver", configurationService.getConfiguration().getString("db.driver"));
        properties.put("javax.persistence.jdbc.url", configurationService.getConfiguration().getString("db.url"));

        final JpaPagingItemReader<List<AbstractCatalogableEntityModel>> entityReader = new JpaPagingItemReader<>();
        entityReader.setEntityManagerFactory(entityManager.getEntityManagerFactory());
        entityReader.setParameterValues(properties);
        entityReader.setQueryString("select p from product p");
        entityReader.setPageSize(1000);

        return entityReader;
    }
```

and when I start the job I see this null pointer exception:

```
java.lang.NullPointerException
	at org.springframework.batch.item.database.JpaPagingItemReader.doReadPage(JpaPagingItemReader.java:196)
	at org.springframework.batch.item.database.AbstractPagingItemReader.doRead(AbstractPagingItemReader.java:108)
	at org.springframework.batch.item.support.AbstractItemCountingItemStreamItemReader.read(AbstractItemCountingItemStreamItemReader.java:83)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:601)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:133)
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:121)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
```

which happens here on `JpaPagingItemReader:196`

```
if (transacted) {
     tx = entityManager.getTransaction();
```

and, yes, the entityManager is `null`. I can see it being instantiated on line 177:

```
entityManager = entityManagerFactory.createEntityManager(jpaPropertyMap);
```

so I put a breakpoint there, but it never goes through that breakpoint so it always stays `null`.

---

**Affects:** 3.0.1

**Comment by henry2man** [comment]
> The open() method of your writer hasn't been called because the writer isn't registered as a stream. Your bean definition method should return an ItemStreamReader instead of ItemReader so it gets registered as a stream automatically.

Hi folks. I've reached this old bug and I think this should be well documented in the `JpaPagingItemReader` class javadoc, isn't it? This change is far from obvious when using this class, and some help in the documentation would not hurt.
