### ISSUE TITLE
.ConcurrencyFailureException: PreparedStatementCallback; SQL [INSERT INTO BATCH_STEP_EXECUTION_CONTEXT  [BATCH-2255]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-batch#1346]
**[Rishi Singhal](https://jira.spring.io/secure/ViewProfile.jspa?name=singhal.rishi@gmail.com)** opened **[BATCH-2255](https://jira.spring.io/browse/BATCH-2255?redirect=false)** and commented

While running our application in parallel we see this issue

```
Caused by: org.springframework.dao.ConcurrencyFailureException: PreparedStatementCallback; SQL [INSERT INTO BATCH_STEP_EXECUTION_CONTEXT (SHORT_CONTEXT, SERIALIZED_CONTEXT, STEP_EXECUTION_ID) VALUES(?, ?, ?)]; transaction rollback: serialization failure; nested exception is java.sql.SQLTransactionRollbackException: transaction rollback: serialization failure
at org.springframework.jdbc.support.SQLExceptionSubclassTranslator.doTranslate(SQLExceptionSubclassTranslator.java:68)
at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:603)
```

---

**Affects:** 2.2.7

**Comment by benas** [comment]
> While running our application in parallel we see this issue

What does your application do? What specifically is running in parallel? It's hard to see from what you shared what the root cause could be. Please provide a minimal complete example to reproduce the issue and we will re-open this issue if necessary.
