### ISSUE TITLE
BackToBackPatternClassifier does not work with delegate that implements Classifier [BATCH-2030]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-batch#1564]
**[Veit Hoffmann](https://jira.spring.io/secure/ViewProfile.jspa?name=vhoff)** opened **[BATCH-2030](https://jira.spring.io/browse/BATCH-2030?redirect=false)** and commented

If BackToBackPatternClassifier has a delegate that inherits from "org.springframework.classify.Classifier" rather than using annotation "org.springframework.classify.annotation.Classifier" the
context creation fails with the Exception in the bottom of this description. The reason seems to be a problem in ClassifierAdapter which is called on setRouterDelegate.
The behavior can be reproduced with the test case attached.

Exception stack trace:

java.lang.IllegalStateException: More than one non-void public method detected with single argument.
at org.springframework.util.Assert.state(Assert.java:384)
at org.springframework.classify.util.MethodInvokerUtils$3.doWith(MethodInvokerUtils.java:202)
at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:473)
at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:481)
at org.springframework.util.ReflectionUtils.doWithMethods(ReflectionUtils.java:451)
at org.springframework.classify.util.MethodInvokerUtils.getMethodInvokerForSingleArgument(MethodInvokerUtils.java:194)
at org.springframework.classify.ClassifierAdapter.setDelegate(ClassifierAdapter.java:84)
at org.springframework.classify.ClassifierAdapter.\<init>(ClassifierAdapter.java:48)
at org.springframework.classify.BackToBackPatternClassifier.setRouterDelegate(BackToBackPatternClassifier.java:72)
at com.generali.appl.referenz.batch.multipleoutput.BackToBackPatternClassifierTests.testSetRouterDelegate(BackToBackPatternClassifierTests.java:48)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.lang.reflect.Method.invoke(Method.java:611)
at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:49)
at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:467)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

---

**Affects:** 3.0.0, 2.2.0.RC2

**Attachments:**
- [BackToBackPatternClassifierTests.java](https://jira.spring.io/secure/attachment/21208/BackToBackPatternClassifierTests.java) (_1006 bytes_)

1 votes, 5 watchers

**Comment by benas** [comment]
Based on the last two comments, I'm closing this issue (as it was reported and fixed in `spring-retry` project: https://github.com/spring-projects/spring-retry/pull/28).
