### ISSUE TITLE
DB2 Version 10 on Z OS Issue with Spring Batch 2.1.8 [BATCH-1790]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-batch#1799]
**[Hema Math](https://jira.spring.io/secure/ViewProfile.jspa?name=hema)** opened **[BATCH-1790](https://jira.spring.io/browse/BATCH-1790?redirect=false)** and commented

When Spring batch is connected to DB2 z os , it has issues when trying to read the sequences created from the db2.schema given in the spring batch.
My Configuration file is as below.

```
<bean id="jobRepository"		class="org.springframework.batch.core.repository.support.JobRepositoryFactoryBean">
<property name="dataSource" ref="dataSource" />
<property name="transactionManager" ref="transactionManager" />
<property name="databaseType" value="DB2ZOS" />
</bean>
```

All the metadata tables that sprin gbatch uses to loge job instances and step details are created in DB2 z os and also the three sequences. All these schema are taken from the db2.schema.

The error what i am getting is.

```
org.springframework.dao.DataIntegrityViolationException: PreparedStatementCallback; SQL [INSERT into BATCH_JOB_INSTANCE(JOB_INSTANCE_ID, JOB_NAME, JOB_KEY, VERSION) values (?, ?, ?, ?)]; DB2 SQL Error: SQLCODE=-803, SQLSTATE=23505, SQLERRMC=IVA204X1;0000000202, DRIVER=3.53.70; nested exception is com.ibm.db2.jcc.b.zn: DB2 SQL Error: SQLCODE=-803, SQLSTATE=23505, SQLERRMC=IVA204X1;0000000202, DRIVER=3.53.70
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:228)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:607)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:792)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:850)
	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:854)
	at org.springframework.batch.core.repository.dao.JdbcJobInstanceDao.createJobInstance(JdbcJobInstanceDao.java:117)
	at org.springframework.batch.core.repository.support.SimpleJobRepository.createJobExecution(SimpleJobRepository.java:131)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

Does it mean that its not able to make call to the sequences created in DB2 z os ?

---

**Affects:** 2.1.8

**Comment by benas** [comment]
Based on the last comment, I'm closing this issue. Feel free to re-open it if necessary with a minimal complete example to reproduce the problem.
