### ISSUE TITLE
MapStepExecutionDao throws an OptimisticLockingFailureException [BATCH-1778]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#1812]
**[Yann Moisan](https://jira.spring.io/secure/ViewProfile.jspa?name=yamo93)** opened **[BATCH-1778](https://jira.spring.io/browse/BATCH-1778?redirect=false)** and commented

Hi,

I use a multi-threaded step (via a ThreadPoolTaskExecutor) and I encountered an unexpected OptimisticLockingFailureException.

According to the javadoc of class MapJobRepositoryFactoryBean, it should work (Not suited for use in multi-threaded jobs with splits, although it should be safe to use in a multi-threaded step).

Here is the configuration of the job repository :

```
<bean id="jobRepository"
     class="org.springframework.batch.core.repository.support.MapJobRepositoryFactoryBean">
     <property name="transactionManager">
          <bean
               class="org.springframework.batch.support.transaction.ResourcelessTransactionManager" />
     </property>
</bean>
```

FYI, I've already encountered a strange behaviour, cf https://jira.springsource.org/browse/BATCH-1774.

```
Here is the stack trace:
org.springframework.dao.OptimisticLockingFailureException: Attempt to update step execution id=2 with wrong version (1), where current version is 2
	at org.springframework.batch.core.repository.dao.MapStepExecutionDao.updateStepExecution(MapStepExecutionDao.java:98)
	at org.springframework.batch.core.repository.support.SimpleJobRepository.update(SimpleJobRepository.java:171)
	at sun.reflect.GeneratedMethodAccessor21.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:37)
	at java.lang.reflect.Method.invoke(Method.java:611)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:309)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:110)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
	at $Proxy1.update(Unknown Source)
	at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:432)
	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:130)
	at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:264)
	at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:76)
	at org.springframework.batch.repeat.support.TaskExecutorRepeatTemplate$ExecutingRunnable.run(TaskExecutorRepeatTemplate.java:257)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:897)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:919)
	at java.lang.Thread.run(Thread.java:736)
```

---

**Affects:** 2.1.7

1 votes, 1 watchers

**Comment by benas** [comment]
The `MapJobRepositoryFactoryBean` and all Map-based DAOs behind it were deprecated in #3780 and will be removed in v5 (#3836), so I see no value in putting efforts on those classes for the rest of their short lifetime. Those classes are not intended for production use anyway (as mentioned in the [Javadoc](https://docs.spring.io/spring-batch/docs/4.3.x/api/org/springframework/batch/core/repository/support/MapJobRepositoryFactoryBean.html) and in [this previous comment](https://github.com/spring-projects/spring-batch/issues/1812#issuecomment-566286712)).
