### ISSUE TITLE
JbdcCursorItemReader is broken in WAS/DB2 envs (probably driver-related) [BATCH-1273]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#2292]
**[David J. M. Karlsen](https://jira.spring.io/secure/ViewProfile.jspa?name=david@davidkarlsen.com)** opened **[BATCH-1273](https://jira.spring.io/browse/BATCH-1273?redirect=false)** and commented

The JdbcCursorItemReader seems broken in WAS envs.
The same test can successfully run as a standalone integration-test, utilzing Bitronix 1.3.2 as XA transaction manager.
It will always fail with a:

```
error code [0]; DSRA9110E: ResultSet is closed.; nested exception is com.ibm.websphere.ce.cm.ObjectClosedException: DSRA9110E: ResultSet is closed.
```

Stack trace:

```
org.springframework.jdbc.UncategorizedSQLException: Attempt to process next row failed; uncategorized SQLException for SQL [
			SELECT PTRAN_PAYMTRANS_ID, PAMSG_MSGID_ORIG, PTRAN_TRANSID_ORIG, PTRAN_RELCNT_PTRAN, PTRAN_RELCNT_PPRTY, 
			PTRAN_RELCNT_PAYAM,PTRAN_EXEC_DATE, PTRAN_SETTLEM_DATE, PTRAN_RELEASE_DATE,CRDEI_CRE_DEB_CODE, PTRAN_STP_INDIC, BANK_ID, PTRAN_VALIDAT_IND, 
			PAYM_DIRECTION_ID, PAYM_TYPE_ID, BASE_CRITERIA_ID, VTGRP_TGROUP_ID, CHRGB_CODE, INHAW_INH_PAWAY_ID, PMPRI_PRIORITY, PSRCC_CATEGORY_ID,  
			SETLM_MECH_ID_CRE, SETLM_MECH_ID_DEB, PRODUCT_BADGE_ID, ORG_UNIT_ID, PTGRP_TOTALGRP_ID, PTRAN_CURRSTATTIME, PTSTA_STATECODCURR, TRSTR_REASON_CODE, 
			PTRAN_TIMELASTCHGE, PTRAN_USERLASTCHGE, PTRAN_PROCESSERVER, PTRAN_OWNINGAPPLID, SELEV_SERVICELEVEL, PTRFT_TRANSFERTYPE, 
			TRDIR_DIRECTION, ACCSC_ACCSYSCATCOD, PAYAM_VALDATE_CRE, CURRENCY_ID_CRE, PAYAM_AMOUNT_CRE, CURRID_CDN_CRE, PAYAM_EXRAT_CRE, PAYAM_EXRATREF_CRE,
			EXRAT_TYPECODE_CRE, CURRID_COUNTVAL_CRE, PAYAM_COUNTVAL_CRE, CDN_COUNTVAL_CRE, PPRTY_ACC_BBAN_CRE, PAYAM_VALDATE_DEB, CURRENCY_ID_DEB, PAYAM_AMOUNT_DEB, 
			CURRID_CDN_DEB, PAYAM_EXRAT_DEB, PAYAM_EXRATREF_DEB, EXRAT_TYPECODE_DEB, CURRID_COUNTVAL_DEB, PAYAM_COUNTVAL_DEB, CDN_COUNTVAL_DEB, PPRTY_ACC_BBAN_DEB, 
			PAYAM_EXRATE_REG, CURRENCY_ID_REG, PAYAM_AMOUNT_REG, CURRID_CDN_REG, EXRAT_TYPECODE_REG, PAYAM_EXRATREF_REG, CURRID_COUNTVAL_REG, 
			PAYAM_COUNTVAL_REG, CDN_COUNTVAL_REG, VALUEDATE_RULE_CRE, VALUEDATE_RULE_DEB, SOURCE_ID
		    FROM PWHSCHEMA.TPWPTRAN WHERE PTSTA_STATECODCURR = ? AND PTRAN_EXEC_DATE = ? AND PTRFT_TRANSFERTYPE = ?
		]; SQL state [null]; error code [0]; DSRA9110E: ResultSet is closed.; nested exception is com.ibm.websphere.ce.cm.ObjectClosedException: DSRA9110E: ResultSet is closed.
at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:83)
at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:80)
at org.springframework.batch.item.database.JdbcCursorItemReader.doRead(JdbcCursorItemReader.java:482)
at org.springframework.batch.item.support.AbstractItemCountingItemStreamItemReader.read(AbstractItemCountingItemStreamItemReader.java:84)
at org.springframework.batch.core.step.item.SimpleChunkProvider.doRead(SimpleChunkProvider.java:90)
at org.springframework.batch.core.step.item.FaultTolerantChunkProvider.read(FaultTolerantChunkProvider.java:53)
at org.springframework.batch.core.step.item.SimpleChunkProvider$1.doInIteration(SimpleChunkProvider.java:106)
at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult(RepeatTemplate.java:352)
at org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:212)
at org.springframework.batch.repeat.support.RepeatTemplate.iterate(RepeatTemplate.java:143)
at org.springframework.batch.core.step.item.SimpleChunkProvider.provide(SimpleChunkProvider.java:103)
at org.springframework.batch.core.step.item.ChunkOrientedTasklet.execute(ChunkOrientedTasklet.java:64)
at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:264)
at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:67)
at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult(RepeatTemplate.java:352)
at org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:212)
at org.springframework.batch.repeat.support.RepeatTemplate.iterate(RepeatTemplate.java:143)
at org.springframework.batch.core.step.tasklet.TaskletStep.doExecute(TaskletStep.java:239)
at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:198)
at org.springframework.batch.core.job.AbstractJob.handleStep(AbstractJob.java:348)
at org.springframework.batch.core.job.flow.FlowJob.access$0(FlowJob.java:1)
at org.springframework.batch.core.job.flow.FlowJob$JobFlowExecutor.executeStep(FlowJob.java:137)
at org.springframework.batch.core.job.flow.support.state.StepState.handle(StepState.java:60)
at org.springframework.batch.core.job.flow.support.SimpleFlow.resume(SimpleFlow.java:144)
at org.springframework.batch.core.job.flow.support.SimpleFlow.start(SimpleFlow.java:124)
at org.springframework.batch.core.job.flow.FlowJob.doExecute(FlowJob.java:105)
at org.springframework.batch.core.job.AbstractJob.execute(AbstractJob.java:250)
at org.springframework.batch.core.configuration.support.ApplicationContextJobFactory$ContextClosingJob.execute(ApplicationContextJobFactory.java:96)
at org.springframework.batch.core.launch.support.SimpleJobLauncher$1.run(SimpleJobLauncher.java:110)
at org.springframework.core.task.SyncTaskExecutor.execute(SyncTaskExecutor.java:49)
at org.springframework.batch.core.launch.support.SimpleJobLauncher.run(SimpleJobLauncher.java:105)
```

---

**Affects:** 2.0.1

4 votes, 6 watchers

**Comment by benas** [comment]
>  it is intended to be used in a completely read-only, forward-only context. I'll make this into a documentation issue.

It seems that the documentation has been updated since this issue was created. Here is an excerpt from the Javadoc of [JdbcCursorItemReader](https://docs.spring.io/spring-batch/docs/current/api/org/springframework/batch/item/database/JdbcCursorItemReader.html):

```
The statement used to open the cursor is created with the 'READ_ONLY' option since a non read-only
cursor may unnecessarily lock tables or rows. It is also opened with 'TYPE_FORWARD_ONLY' option.
```
