### ISSUE TITLE
On Spring Batch 2.1.8.RELEASE, @Scope(value = "step") vs. @StepScope do not work the same

### ISSUE THREAD

**Issue by crispi-drivin** [spring-projects/spring-batch#3651]
On . processor implementation class, I add 
`@Scope(value = "step")` and it threw the following error:
```
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-01-27 11:24:59.634 ERROR 8407 --- [  restartedMain] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'jobLauncherController': Unsatisfied dependency expressed through field 'job'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'migrateSalesforceData' defined in class path resource [com/autoniq/migration/autoniqusermigration/config/AutoniqUserMigrationBatchConfig.class]: Unsatisfied dependency expressed through method 'migrateSalesforceData' parameter 37; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'storeUserAppSettingsSuccessResults' defined in class path resource [com/autoniq/migration/autoniqusermigration/config/SalesforceStepsConfig.class]: Unsatisfied dependency expressed through method 'storeUserAppSettingsSuccessResults' parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'userAppSettingsSuccessProcessor': Scope 'step' is not active for the current thread; consider defining a scoped proxy for this bean if you intend to refer to it from a singleton; nested exception is java.lang.IllegalStateException: No context holder available for step scope
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:596)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:374)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1411)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:592)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:845)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:877)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:744)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:391)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1204)
	at com.autoniq.migration.autoniqusermigration.AutoniqUserMigrationApplication.main(AutoniqUserMigrationApplication.java:10)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'migrateSalesforceData' defined in class path resource [com/autoniq/migration/autoniqusermigration/config/AutoniqUserMigrationBatchConfig.class]: Unsatisfied dependency expressed through method 'migrateSalesforceData' parameter 37; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'storeUserAppSettingsSuccessResults' defined in class path resource [com/autoniq/migration/autoniqusermigration/config/SalesforceStepsConfig.class]: Unsatisfied dependency expressed through method 'storeUserAppSettingsSuccessResults' parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'userAppSettingsSuccessProcessor': Scope 'step' is not active for the current thread; consider defining a scoped proxy for this bean if you intend to refer to it from a singleton; nested exception is java.lang.IllegalStateException: No context holder available for step scope
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:769)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:509)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1321)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1160)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:277)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1251)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1171)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:593)
	... 24 common frames omitted
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'storeUserAppSettingsSuccessResults' defined in class path resource [com/autoniq/migration/autoniqusermigration/config/SalesforceStepsConfig.class]: Unsatisfied dependency expressed through method 'storeUserAppSettingsSuccessResults' parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'userAppSettingsSuccessProcessor': Scope 'step' is not active for the current thread; consider defining a scoped proxy for this bean if you intend to refer to it from a singleton; nested exception is java.lang.IllegalStateException: No context holder available for step scope
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:769)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:509)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1321)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1160)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:277)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1251)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1171)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:857)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:760)
	... 37 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'userAppSettingsSuccessProcessor': Scope 'step' is not active for the current thread; consider defining a scoped proxy for this bean if you intend to refer to it from a singleton; nested exception is java.lang.IllegalStateException: No context holder available for step scope
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:365)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:277)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1251)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1171)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:857)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:760)
	... 51 common frames omitted
Caused by: java.lang.IllegalStateException: No context holder available for step scope
	at org.springframework.batch.core.scope.StepScope.getContext(StepScope.java:167)
	at org.springframework.batch.core.scope.StepScope.get(StepScope.java:99)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:353)
	... 57 common frames omitted
```

However, changing the annotation to `@StepScope` fixed the error and the batch application ran with no errors.

**Comment by mminella** [comment]
@crispi-drivin Can you please provide a skeleton class that illustrates the code you saw this issue on?

**Comment by crispi-drivin** [comment]
Sure: 
```
@Component
@StepScope //this annotation works
//@Scope(value = "step") //this does not
public class SomeObjectProcessor implements ItemProcessor<InputObj, OutputObj> {
	
	private String runDateTime;
	
	public SomeObjectProcessor(@Value("#{jobParameters['runDateTime']}") String runDateTime) {
		this.runDateTime = runDateTime;
	}

	@Override
	public OutputObj process(InputObj item) throws Exception {
		SomeObj request = new SomeObj();
		request.setRunDateTime(runDateTime);

		return new OutputObj(request);
	}
}
`

Step config code:
```
@Configuration
public class StepsConfig {
	@Autowired
	private StepBuilderFactory steps;

	@Bean
	protected Step doSomethingWithSomeObject(ItemReader<InputObj> inputObjReader,
			ItemProcessor<InputObj, OutputObj> someObjectProcessor, ItemWriter<OutputObj> outputObjWriter) {
		return steps.get(STEP_DO_SOMETHING).<InputObj, OutputObj>chunk(10).reader(inputObjReader)
				.processor(someObjectProcessor).writer(outputObjWriter).build();
	}
}
`

Job config code:
```
@Configuration
@EnableBatchProcessing
public class MyAppBatchConfig {
	@Autowired
	private JobBuilderFactory jobs;

	@Autowired
	private JobRepository jobRepository;

	@Bean(name = "doSomething")
	public Job doSomethingJob(Step doSomethingWithSomeObject) {
		return jobs.get("doSomething")
				.start(doSomethingWithSomeObject)
				.build();
	}
`

**Comment by benas** [comment]
> On Spring Batch 2.1.8.RELEASE

Spring Batch v2 and v3 are not maintained anymore. Do you have the issue with v4+?

**Comment by mminella** [comment]
Per the java doc for `@StepScope`, the equivalent configuration is `@Scope(value="step", proxyMode=TARGET_CLASS)`.  We are closing this as works as designed.
