### ISSUE TITLE
The constructor of JsonItemReader should call setExecutionContextName()

### ISSUE THREAD

**Issue by benelog** [spring-projects/spring-batch#3681]
When the constructor of JsonItemReader is called directly and  `open(ExectionConext)` is called, it makes exceptions at `ExecutionContextUserSupport.getKey(..)`

```java
    JsonItemReader<AccessLog> reader = new JsonItemReader<AccessLog>(resource, jsonObjectReader);
    reader.open(new ExecutionContext());
    AccessLog item = reader.read();
    reader.close();
```

```
java.lang.IllegalArgumentException: Name must be assigned for the sake of defining the execution context keys prefix.

	at org.springframework.util.Assert.hasText(Assert.java:284)
	at org.springframework.batch.item.util.ExecutionContextUserSupport.getKey(ExecutionContextUserSupport.java:62)
	at org.springframework.batch.item.ItemStreamSupport.getExecutionContextKey(ItemStreamSupport.java:71)
	at org.springframework.batch.item.support.AbstractItemCountingItemStreamItemReader.open(AbstractItemCountingItemStreamItemReader.java:159)
```
The constructor of JsonItemReader should call `setExecutionContextName(String)` similar to [JsonFileItemWriter.java#L71](https://github.com/spring-projects/spring-batch/blob/master/spring-batch-infrastructure/src/main/java/org/springframework/batch/item/json/JsonFileItemWriter.java#L71)

**Comment by benas** [comment]
Good catch. This is indeed enforced in the builder but not in the constructor. Thank you for raising this issue and for opening a PR! I will take a look asap.
