### ISSUE TITLE
Deadlock，Multi-thread Step

### ISSUE THREAD

**Issue by 272711697** [spring-projects/spring-batch#3769]
version：4.1.2 release;
main thread stack:
"http-nio-8081-exec-322" #64563 daemon prio=5 os_prio=0 tid=0x00007f563004b800 nid=0x71c1 waiting on condition [0x00007f55cf5c6000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000000e8c21068> (a java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.PriorityBlockingQueue.take(PriorityBlockingQueue.java:549)
	at org.springframework.batch.repeat.support.ResultHolderResultQueue.take(ResultHolderResultQueue.java:129)
	- locked <0x00000000e8c21098> (a java.lang.Object)
	at org.springframework.batch.repeat.support.ResultHolderResultQueue.take(ResultHolderResultQueue.java:33)
	at org.springframework.batch.repeat.support.TaskExecutorRepeatTemplate.waitForResults(TaskExecutorRepeatTemplate.java:172)
	at org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:232)
	at org.springframework.batch.repeat.support.RepeatTemplate.iterate(RepeatTemplate.java:145)
	at org.springframework.batch.core.step.tasklet.TaskletStep.doExecute(TaskletStep.java:258)
	at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:203)
	at org.springframework.batch.core.job.SimpleStepHandler.handleStep(SimpleStepHandler.java:148)
	at org.springframework.batch.core.job.flow.JobFlowExecutor.executeStep(JobFlowExecutor.java:68)
	at org.springframework.batch.core.job.flow.support.state.StepState.handle(StepState.java:67)
	at org.springframework.batch.core.job.flow.support.SimpleFlow.resume(SimpleFlow.java:169)
	at org.springframework.batch.core.job.flow.support.SimpleFlow.start(SimpleFlow.java:144)
	at org.springframework.batch.core.job.flow.FlowJob.doExecute(FlowJob.java:136)
	at org.springframework.batch.core.job.AbstractJob.execute(AbstractJob.java:313)
	at org.springframework.batch.core.launch.support.SimpleJobLauncher$1.run(SimpleJobLauncher.java:144)
	at org.springframework.core.task.SyncTaskExecutor.execute(SyncTaskExecutor.java:50)
	at org.springframework.batch.core.launch.support.SimpleJobLauncher.run(SimpleJobLauncher.java:137)

TaskExecutor thread stack:
"pay-task-71" #31684 prio=5 os_prio=0 tid=0x00007f5658750000 nid=0xddaa waiting for monitor entry [0x00007f55cffd2000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at org.springframework.batch.repeat.support.ResultHolderResultQueue.put(ResultHolderResultQueue.java:97)
	- waiting to lock <0x00000000e8c21098> (a java.lang.Object)
	at org.springframework.batch.repeat.support.ResultHolderResultQueue.put(ResultHolderResultQueue.java:33)
	at org.springframework.batch.repeat.support.TaskExecutorRepeatTemplate$ExecutingRunnable.run(TaskExecutorRepeatTemplate.java:274)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
	- <0x00000000ccc7a130> (a java.util.concurrent.ThreadPoolExecutor$Worker)

"pay-task-70" #31683 prio=5 os_prio=0 tid=0x00007f565877f800 nid=0xdda9 waiting for monitor entry [0x00007f55d20e9000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at org.springframework.batch.repeat.support.ResultHolderResultQueue.put(ResultHolderResultQueue.java:97)
	- waiting to lock <0x00000000e8c21098> (a java.lang.Object)
	at org.springframework.batch.repeat.support.ResultHolderResultQueue.put(ResultHolderResultQueue.java:33)
	at org.springframework.batch.repeat.support.TaskExecutorRepeatTemplate$ExecutingRunnable.run(TaskExecutorRepeatTemplate.java:274)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
	- <0x00000000ccc7a0a0> (a java.util.concurrent.ThreadPoolExecutor$Worker)

"pay-task-48" #137 prio=5 os_prio=0 tid=0x00007f564403a000 nid=0x1748e waiting for monitor entry [0x00007f55d3dfe000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at org.springframework.batch.repeat.support.ResultHolderResultQueue.put(ResultHolderResultQueue.java:97)
	- waiting to lock <0x00000000e8c21098> (a java.lang.Object)
	at org.springframework.batch.repeat.support.ResultHolderResultQueue.put(ResultHolderResultQueue.java:33)
	at org.springframework.batch.repeat.support.TaskExecutorRepeatTemplate$ExecutingRunnable.run(TaskExecutorRepeatTemplate.java:274)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
	- <0x00000000c2d9d930> (a java.util.concurrent.ThreadPoolExecutor$Worker)

"pay-task-32" #117 prio=5 os_prio=0 tid=0x00007f5650006000 nid=0x1747b waiting for monitor entry [0x00007f55d91e1000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at org.springframework.batch.repeat.support.ResultHolderResultQueue.put(ResultHolderResultQueue.java:97)
	- waiting to lock <0x00000000e8c21098> (a java.lang.Object)
	at org.springframework.batch.repeat.support.ResultHolderResultQueue.put(ResultHolderResultQueue.java:33)
	at org.springframework.batch.repeat.support.TaskExecutorRepeatTemplate$ExecutingRunnable.run(TaskExecutorRepeatTemplate.java:274)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
	- <0x00000000c2d9dba0> (a java.util.concurrent.ThreadPoolExecutor$Worker)

**Comment by benas** [comment]
Hi @272711697 ,

Thank you for opening this issue. However, this does not help us too much in understanding the cause of the problem. Please provide a minimal example that reproduces the issue and we can dig deeper. Thank you.
