### ISSUE TITLE
Please add java.util.Locale to the list of trusted classes.

### ISSUE THREAD

**Issue by ptahchiev** [spring-projects/spring-batch#3786]
I get the following exception whenever I try to run my jobs:
```
Caused by: java.lang.IllegalArgumentException: The class with java.util.Locale and name of java.util.Locale is not trusted. If you believe this class is safe to deserialize, please provide an explicit mapping using Jackson annotations or a custom ObjectMapper. If the serialization is only done by a trusted source, you can also enable default typing.
	at org.springframework.batch.core.repository.dao.Jackson2ExecutionContextStringSerializer$TrustedTypeIdResolver.typeFromId(Jackson2ExecutionContextStringSerializer.java:329)
	at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._findDeserializer(TypeDeserializerBase.java:156)
	at com.fasterxml.jackson.databind.jsontype.impl.AsArrayTypeDeserializer._deserialize(AsArrayTypeDeserializer.java:97)
	at com.fasterxml.jackson.databind.jsontype.impl.AsArrayTypeDeserializer.deserializeTypedFromArray(AsArrayTypeDeserializer.java:53)
	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromAny(AsPropertyTypeDeserializer.java:191)
	at com.fasterxml.jackson.databind.deser.std.UntypedObjectDeserializer$Vanilla.deserializeWithType(UntypedObjectDeserializer.java:712)
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:529)
	... 156 more

```

and it seems like there's a list of trusted classes here:
https://github.com/spring-projects/spring-batch/blob/master/spring-batch-core/src/main/java/org/springframework/batch/core/repository/dao/Jackson2ExecutionContextStringSerializer.java#L243

Would be great if `java.util.Locale` was part of the trusted classes.

**Comment by benas** [comment]
Instead of adding individual classes on demand like here, we are going to provide a mechanism to extend the base list of trusted classes as described in #3765. BTW, I used this use case to test the new approach [here](https://github.com/spring-projects/spring-batch/pull/3787/files#diff-08f0d87a1763efa17e30f7df48e7b794R80).

So I'm closing this issue in favor of #3765 .
