### ISSUE TITLE
Remote Chunking runs in to issue when deserializing the ChunkResponse

### ISSUE THREAD

**Issue by ajain72** [spring-projects/spring-batch#3793]
Please do a quick search on Github issues first, there might be already a duplicate issue for the one you are about to create.
If the bug is trivial, just go ahead and create the issue. Otherwise, please take a few moments and fill in the following sections:

**Bug description**
While trying the Remote Chunking in Spring Batch Integration, ran in to the issue where ChunkResponse JSON string can not be deserialized because it doesn't have the default no arg constructor.

```
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `org.springframework.batch.integration.chunk.ChunkResponse` (no Creators, like default constructor, exist): no String-argument constructor/factory method to deserialize from String value ('{"jobId":1,"items":[{"servicerId":"14803","fhaCaseNumber":"167-8501566"}],"stepContribution":{"readCount":0,"writeCount":0,"filterCount":0,"readSkipCount":0,"writeSkipCount":0,"processSkipCount":0,"exitStatus":{"exitCode":"EXECUTING","exitDescription":"","running":true},"stepExecution":{"id":1,"version":1,"stepName":"stepOne","status":"STARTED","readCount":0,"writeCount":0,"commitCount":0,"rollbackCount":0,"readSkipCount":0,"processSkipCount":0,"writeSkipCount":0,"startTime":1602856616533,"endTime":null,"lastUpdated":1602856616533,"executionContext":{"dirty":true,"empty":false},"exitStatus":{"exitCode":"EXECUTING","exitDescription":"","running":true},"terminateOnly":false,"filterCount":0,"failureExceptions":[],"jobParameters":{"parameters":{"run.id":{"identifying":true,"value":1,"type":"LONG"}},"empty":false},"summary":"StepExecution: id=1, version=1, name=stepOne, status=STARTED, exitStatus=EXECUTING, readCount=0, filterCount=0, writeCount=0 readSkipCount=0, writeSkipCount=0, processSkipCount=0, commitCount=0, rollbackCount=0","jobExecutionId":1,"skipCount":0},"skipCount":0,"stepSkipCount":0},"sequence":0}')
 at [Source: (String)""{\"jobId\":1,\"items\":[{\"myId\":\"14803\"}],\"stepContribution\":{\"readCount\":0,\"writeCount\":0,\"filterCount\":0,\"readSkipCount\":0,\"writeSkipCount\":0,\"processSkipCount\":0,\"exitStatus\":{\"exitCode\":\"EXECUTING\",\"exitDescription\":\"\",\"running\":true},\"stepExecution\":{\"id\":1,\"version\":1,\"stepName\":\"stepOne\",\"status\":\"STARTED\",\"readCount\":0,\"writeCount\":0,\"commitCount\":0,\"rollbackCount\":0,\"readSkipCount\":0,\"process"[truncated 752 chars]; line: 1, column: 1]
	at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:67)
	at com.fasterxml.jackson.databind.DeserializationContext.reportBadDefinition(DeserializationContext.java:1615)
	at com.fasterxml.jackson.databind.DatabindContext.reportBadDefinition(DatabindContext.java:400)
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1077)
	at com.fasterxml.jackson.databind.deser.ValueInstantiator._createFromStringFallbacks(ValueInstantiator.java:371)
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromString(StdValueInstantiator.java:323)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromString(BeanDeserializerBase.java:1408)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:176)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:166)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4524)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3466)
	at org.springframework.integration.support.json.Jackson2JsonObjectMapper.fromJson(Jackson2JsonObjectMapper.java:135)
	at org.springframework.integration.support.json.Jackson2JsonObjectMapper.fromJson(Jackson2JsonObjectMapper.java:67)
	at org.springframework.integration.support.json.AbstractJacksonJsonObjectMapper.fromJson(AbstractJacksonJsonObjectMapper.java:67)
	at org.springframework.integration.json.JsonToObjectTransformer.doTransform(JsonToObjectTransformer.java:174)
	... 21 more
```

============
Other attributes in ChunkResponse such as StepContribution run in to the same issue if I were to go past ChunkResponse somehow.
Exception in thread "main" com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `org.springframework.batch.core.StepContribution` (no Creators, like default constructor, exist): cannot deserialize from Object value (no delegate- or property-based Creator)

**Environment**
Please provide as many details as possible: Spring Batch version, Java version, which database you use if any, etc.

Spring Batch/Integration within Spring Boot env. Using SQS as transport between Manager and Worker. Examples included in the documentation use AMQ/JMS and uses JAVA OBJECT Serialization which isn't an option in a distributed.

	id 'org.springframework.boot' version '2.3.4.RELEASE'
	id 'io.spring.dependency-management' version '1.0.10.RELEASE'

	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'org.springframework.boot:spring-boot-starter-batch'
	implementation 'org.springframework.cloud:spring-cloud-starter-aws-messaging'
	implementation 'org.springframework.boot:spring-boot-starter-integration'
	compile 'org.springframework.batch:spring-batch-integration:4.2.4.RELEASE'
	compile 'org.springframework.integration:spring-integration-aws:2.3.3.RELEASE'
	compile 'com.amazonaws:aws-java-sdk-core:1.11.880'
	compile 'com.amazonaws:aws-java-sdk-sqs:1.11.880'

**Steps to reproduce**
Steps to reproduce the issue.
Add MappingJackson2MessageConverter for outbound message. Had to deal with MixIns and another issue to get this working. It was pretty painful to get the outbound message conversion to JSON working.

And on it's way back, add the Transformer.

	@Bean
	@Transformer(inputChannel = "sqs_replies", outputChannel = "replies", poller = @Poller(fixedDelay = "1000"))
	public org.springframework.integration.transformer.Transformer fromJson() {
		return new JsonToObjectTransformer(ChunkResponse.class, new Jackson2JsonObjectMapper(objectMapper()));
	}

**Expected behavior**
If ChunkResponse and StepContribution and other objects in the graph had a default Constructor it should just work, i.e. JsonToObjectTransformer will map the incoming JSON payload to ChunkResponse.

**Minimal Complete Reproducible example**
Please provide a failing unit test or a [minimal complete example](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the issue.
Reports that are reproducible will take priority over reports that are not reproducible.

STEPS to reproduce : add a JSON Converter for outbound messages and inbound messages.  

	@Bean
	@Transformer(inputChannel = "sqs_replies", outputChannel = "replies", poller = @Poller(fixedDelay = "1000"))
	public org.springframework.integration.transformer.Transformer fromJson() {
		return new JsonToObjectTransformer(ChunkResponse.class, new Jackson2JsonObjectMapper(objectMapper()));
	}

A simple unit test of course demonstrates the issue -

```java
import static org.junit.Assert.assertTrue;

import org.junit.jupiter.api.Test;
import org.springframework.batch.integration.chunk.ChunkResponse;

import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.ObjectMapper;


public class Json2ObjectMappingTest {

	public static String jsonChunkResponse = "{\"jobId\":1,\"items\":[{\"myId\":\"14803\"],\"stepContribution\":{\"readCount\":0,\"writeCount\":0,\"filterCount\":0,\"readSkipCount\":0,\"writeSkipCount\":0,\"processSkipCount\":0,\"exitStatus\":{\"exitCode\":\"EXECUTING\",\"exitDescription\":\"\",\"running\":true},\"stepExecution\":{\"id\":1,\"version\":1,\"stepName\":\"stepOne\",\"status\":\"STARTED\",\"readCount\":0,\"writeCount\":0,\"commitCount\":0,\"rollbackCount\":0,\"readSkipCount\":0,\"processSkipCount\":0,\"writeSkipCount\":0,\"startTime\":1602803828546,\"endTime\":null,\"lastUpdated\":1602803828547,\"executionContext\":{\"dirty\":true,\"empty\":false},\"exitStatus\":{\"exitCode\":\"EXECUTING\",\"exitDescription\":\"\",\"running\":true},\"terminateOnly\":false,\"filterCount\":0,\"failureExceptions\":[],\"jobExecutionId\":1,\"skipCount\":0,\"jobParameters\":{\"parameters\":{\"run.id\":{\"identifying\":true,\"value\":1,\"type\":\"LONG\"}},\"empty\":false},\"summary\":\"StepExecution: id=1, version=1, name=stepOne, status=STARTED, exitStatus=EXECUTING, readCount=0, filterCount=0, writeCount=0 readSkipCount=0, writeSkipCount=0, processSkipCount=0, commitCount=0, rollbackCount=0\"},\"skipCount\":0,\"stepSkipCount\":0},\"sequence\":0}";

	private  ObjectMapper objectMapper(){
		ObjectMapper mapper = new ObjectMapper();
		return mapper.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false);
	}
	@Test
	void fromJsonToObject() throws Exception{
		try {
			ChunkResponse cr = objectMapper().readValue(jsonChunkResponse, ChunkResponse.class);
			assertTrue(false);
		}catch(Exception e) {
			e.printStackTrace();
			assertTrue(true);
		}
				
	}
}
```

**Comment by mvigneshtuty** [comment]
@ajain72  Are you able to solve this issue? any workaround possible?

**Comment by PascoalBayonne** [comment]
Is there any workaround? Any example would be very nice

**Comment by ajain72** [comment]
It has been a while; I don't remember all the details. I finally gave up on this because there were quite a few issues while using JSON.

**Comment by benas** [comment]
This is a Jackson issue, not a Spring Batch issue (similar to https://github.com/spring-projects/spring-batch/issues/1488#issuecomment-566278703). Other libraries are able to serialize/deserialize `ChunkResponse` objects, here is a quick example with `Gson`:

```
package org.springframework.batch.sample;

import java.io.IOException;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.google.gson.Gson;

import org.springframework.batch.core.JobExecution;
import org.springframework.batch.core.JobInstance;
import org.springframework.batch.core.JobParameters;
import org.springframework.batch.core.JobParametersBuilder;
import org.springframework.batch.core.StepContribution;
import org.springframework.batch.core.StepExecution;
import org.springframework.batch.integration.chunk.ChunkResponse;

public class TestChunkResponseSerializationDeserialization {

    public static void main(String[] args) throws IOException {
        long id = 123L;
        JobInstance jobInstance = new JobInstance(id, "myJob");
        JobParameters jobParameters = new JobParametersBuilder()
                .addString("name", "foo")
                .toJobParameters();
        JobExecution jobExecution = new JobExecution(jobInstance, jobParameters);
        StepExecution stepExecution = new StepExecution("myStep", jobExecution);
        StepContribution stepContribution = stepExecution.createStepContribution();
        ChunkResponse chunkResponse = new ChunkResponse(123, id, stepContribution);

        // Gson
        Gson gson = new Gson();
        String serializedGson = gson.toJson(chunkResponse);
        System.out.println("serializedGson = " + serializedGson);
        ChunkResponse deserializedGson = gson.fromJson(serializedGson, ChunkResponse.class);
        System.out.println("deserializedGson = " + deserializedGson);

        // Jackson
        ObjectMapper objectMapper = new ObjectMapper();
        String serializedJackson = objectMapper.writeValueAsString(chunkResponse);
        System.out.println("serializedJackson = " + serializedJackson);
        ChunkResponse deserializedJackson = objectMapper.readValue(serializedJackson, ChunkResponse.class);
        System.out.println("deserializedJackson = " + deserializedJackson); // fails with com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `org.springframework.batch.integration.chunk.ChunkResponse` (no Creators, like default constructor, exist): no String-argument constructor/factory method to deserialize from String value
    }
}

```

This prints the following output from `Gson`:

```
serializedGson = {"stepContribution":{"readCount":0,"writeCount":0,"filterCount":0,"parentSkipCount":0,"readSkipCount":0,"writeSkipCount":0,"processSkipCount":0,"exitStatus":{"exitCode":"EXECUTING","exitDescription":""},"stepExecution":{"jobExecution":{"jobParameters":{"parameters":{"name":{"parameter":"foo","parameterType":"STRING","identifying":true}}},"jobInstance":{"jobName":"myJob","id":123},"stepExecutions":[],"status":"STARTING","createTime":"May 18, 2022, 6:08:08 AM","exitStatus":{"exitCode":"UNKNOWN","exitDescription":""},"executionContext":{"dirty":false,"map":{}}},"stepName":"myStep","status":"STARTING","readCount":0,"writeCount":0,"commitCount":0,"rollbackCount":0,"readSkipCount":0,"processSkipCount":0,"writeSkipCount":0,"createTime":"May 18, 2022, 6:08:08 AM","executionContext":{"dirty":false,"map":{}},"exitStatus":{"exitCode":"EXECUTING","exitDescription":""},"terminateOnly":false,"filterCount":0}},"jobId":123,"status":true,"redelivered":false,"sequence":123}
deserializedGson = ChunkResponse: jobId=123, sequence=123, stepContribution=[StepContribution: read=0, written=0, filtered=0, readSkips=0, writeSkips=0, processSkips=0, exitStatus=EXECUTING], successful=true
```

and fails for the same object with Jackson. I did not try other libraries, but this is enough to show that the issue is not related to Spring Batch per se. Not all libraries are able to handle objects with no default constructor or object graphs with bi-directional relations, so it is up to the user to choose the right library for the job (or teach Jackson how to handle such objects).

**Comment by PascoalBayonne** [comment]
Still the same, even Gson cannot serialize ChunkRequest. Remeber that chunkResponse works well.
