### ISSUE TITLE
FlatFileItemWriter which use GoogleCloudResource throw java.lang.UnsupportedOperationException

### ISSUE THREAD

**Issue by szopal** [spring-projects/spring-batch#3854]
Hi, 

I would like to use FlatFileItemWriter to write files to Google Cloud Storage, but when I use GoogleCloudResource in FlatFileItemWriterBuilder it throw me error:

```
    final String location = "gs://my-bucket/myfile"
    final Storage storage = StorageOptions.newBuilder().setCredentials(GoogleCredentials.getApplicationDefault()).build().getService();

    final Resource resource = new GoogleStorageResource(storage, location);

    // @formatter:off
    return new FlatFileItemWriterBuilder<Ebhdc>()
        .name("myWriter")
        .resource(resource)
        .formatted().format(


Caused by: java.lang.UnsupportedOperationException: gs://my-bucket/myfile cannot be resolved to absolute file path
	at org.springframework.cloud.gcp.storage.GoogleStorageResource.getFile(GoogleStorageResource.java:230)
	at org.springframework.batch.item.support.AbstractFileItemWriter.getOutputState(AbstractFileItemWriter.java:367)
	at org.springframework.batch.item.support.AbstractFileItemWriter.write(AbstractFileItemWriter.java:237)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:136)
	at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:124)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy133.write(Unknown Source)
	at org.springframework.batch.core.step.item.SimpleChunkProcessor.writeItems(SimpleChunkProcessor.java:193)
	at org.springframework.batch.core.step.item.SimpleChunkProcessor.doWrite(SimpleChunkProcessor.java:159)
	at org.springframework.batch.core.step.item.FaultTolerantChunkProcessor$3.doWithRetry(FaultTolerantChunkProcessor.java:336)
	at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:287)
```

I would like to use local file and Google Cloud Storage dynamically, without create two writers - one for local files second for Google Cloud Storage (nowadays I can write to Google Cloud Storage by use this https://github.com/ncelq/spring-batch-gcs/blob/master/src/main/java/com/cloud/sample/GSFileWriter.java).

**Comment by santfirax** [comment]
Hello @benas I would like to work on this issue. Any chance that you can provide some guidance?

**Comment by santfirax** [comment]
Hello @szopal I was looking at the code and getFile is not implemented yet. Would you tell me what is your use case? do you want to retrieve a file from google storage and write some info or do you want to save files into a bucket in google cloud ?

**Comment by szopal** [comment]
Hello,

I would like both - read file from GCS bucket (Google Cloud Storage) and next write file to GCS bucket.

I write some method for read from GCS by ReadChannel and next set this as Resource but in ItemWriter this not work, so I used ItemWriter from above exemple but I have to have both ItemWriter - for running locally without GCS and to run with using GCS.

**Comment by benas** [comment]
@szopal Thank you for opening this issue. The `FlatFileItemWriter` is designed to work against `Resource` implementations that represent a writable file. Here is an excerpt from its [Javadoc](https://docs.spring.io/spring-batch/docs/4.3.x/api/org/springframework/batch/item/file/FlatFileItemWriter.html):

```
The location of the output file is defined by a Resource and must represent a writable file.
```

The resource implementation you provided (`GoogleStorageResource`) does not seem to represent a writable file as expected by the `FlatFileItemWriter`, since its [throws an `UnsupportedOperationException` for `getFile()`](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/blob/main/spring-cloud-gcp-storage/src/main/java/com/google/cloud/spring/storage/GoogleStorageResource.java#L254).

So I don't see what could be done in Spring Batch for that. Hence, I'm closing this issue.

@santfirax Thank you for your offer to help on this! I believe if your [PR](https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/436) against spring cloud GCP is accepted, then the `GoogleStorageResource` could be used with the `FlatFileItemWriter`.
