### ISSUE TITLE
Intermittent failure in TaskExecutorRepeatTemplateAsynchronousTests

### ISSUE THREAD

**Issue by fmbenhassine** [spring-projects/spring-batch#3866]
`TaskExecutorRepeatTemplateAsynchronousTests#testThrottleLimit` fails intermittently with an `ArrayIndexOutOfBoundsException`, see [build log](https://build.spring.io/browse/BATCH-NIGHTLY-JOB1-5128/test/case/290164400).

**Comment by hpoettker** [comment]
The error that I can reproduce by executing the test thousands of times is:

```
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 0
  at java.base/java.util.ArrayList.add(ArrayList.java:455)
  at java.base/java.util.ArrayList.add(ArrayList.java:467)
  at org.springframework.batch.repeat.support.TaskExecutorRepeatTemplateAsynchronousTests$6.doInIteration(TaskExecutorRepeatTemplateAsynchronousTests.java:187)
  at org.springframework.batch.repeat.support.TaskExecutorRepeatTemplate$ExecutingRunnable.run(TaskExecutorRepeatTemplate.java:261)
  at org.springframework.core.task.SimpleAsyncTaskExecutor$ConcurrencyThrottlingRunnable.run(SimpleAsyncTaskExecutor.java:285)
  at java.base/java.lang.Thread.run(Thread.java:833)
```

It's thrown here: https://github.com/spring-projects/spring-batch/blob/e67c0069f1611c31ee364a9ecce0cec2bd707114/spring-batch-infrastructure/src/test/java/org/springframework/batch/repeat/support/TaskExecutorRepeatTemplateAsynchronousTests.java#L187

The issue seems to be that the callback is executed concurrently while `items` and `threadNames` are not thread-safe collections.
