### ISSUE TITLE
springbatch remotepartition polling‘s bug

### ISSUE THREAD

**Issue by ThomasYoung1989** [spring-projects/spring-batch#4006]
I‘m using remotepartition polling;When the size of partition is less than 100,it works well;When the size is bigger,some of the partitionSteps  remained 'STARTING' status,and the size is random; here is my woker configuration：

`

   /**
     *TaskExecutor
     */
    @Bean(name = "remoteStepBillTaskExecutor")
    public ThreadPoolTaskExecutor remoteStepBillTaskExecutor() {
        ThreadPoolTaskExecutor executor = new ThreadPoolTaskExecutor();
        executor.setCorePoolSize(30);
        executor.setMaxPoolSize(30);
        executor.setQueueCapacity(200);
        executor.setKeepAliveSeconds(30000);
        executor.setThreadNamePrefix("RemoteAsyncStepBillExecutor");
        return executor;
    }

 /*
     * Configure inbound flow (requests coming from the master)
     */
    @Bean
    public ExecutorChannel partitionInBillWorkerRequests() {
        return new ExecutorChannel(remoteStepBillTaskExecutor());
    }

    @Bean
    public IntegrationFlow inboundFlow(@Autowired ConnectionFactory connectionFactory) {
        return IntegrationFlows
                .from(Amqp.inboundAdapter(connectionFactory,RiskBillTaskQueue.RiskBillTaskConstant.IN_BILL_PARTITION_WORKERINQUEUE))
                .channel(partitionInBillWorkerRequests())
                .get();
    }
`

**Comment by ThomasYoung1989** [comment]
i know why; When the woker throw exception,the job will never complete;here is my exception:
`org.springframework.messaging.MessageHandlingException: nested exception is org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLTransientConnectionException: hikaricp - Connection is not available, request timed out after 30000ms., failedMessage=GenericMessage [payload=StepExecutionRequest: [jobExecutionId=752778, stepExecutionId=3547918, stepName=partitionInbillWorkerStep], headers={amqp_receivedDeliveryMode=PERSISTENT, sequenceNumber=52, amqp_receivedExchange=in_bill_partition_manager_exchange, amqp_deliveryTag=70, sequenceSize=201, amqp_consumerQueue=in_bill_partition_batch_worker_queue, amqp_redelivered=false, amqp_timestamp=Fri Sep 24 13:44:30 CST 2021, amqp_messageId=d1976dbf-e3b8-be06-aa91-a88d70abcfcb, correlationId=752778:partitionInbillWorkerStep, id=578c4fd5-7925-1bb7-1924-c9f850e26a13, amqp_consumerTag=amq.ctag-waUZx5ZUlgL5t44MVCGfIA, contentType=application/x-java-serialized-object, timestamp=1632462270755}]
        at org.springframework.integration.handler.MethodInvokingMessageProcessor.processMessage(MethodInvokingMessageProcessor.java:109)
        at org.springframework.integration.handler.ServiceActivatingHandler.handleRequestMessage(ServiceActivatingHandler.java:93)
        at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:123)
        at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:169)
        at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:115)
        at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:132)
        at org.springframework.integration.dispatcher.UnicastingDispatcher.access$000(UnicastingDispatcher.java:52)
        at org.springframework.integration.dispatcher.UnicastingDispatcher$1.run(UnicastingDispatcher.java:113)
        at org.springframework.integration.util.ErrorHandlingTaskExecutor.lambda$execute$0(ErrorHandlingTaskExecutor.java:57)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLTransientConnectionException: hikaricp - Connection is not available, request timed out after 30000ms.
        at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:82)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:612)
        at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:669)
        at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:700)
        at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:728)
        at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:738)
        at org.springframework.batch.core.repository.dao.JdbcJobExecutionDao.getJobParameters(JdbcJobExecutionDao.java:390)
        at org.springframework.batch.core.repository.dao.JdbcJobExecutionDao$JobExecutionRowMapper.mapRow(JdbcJobExecutionDao.java:420)
        at org.springframework.batch.core.repository.dao.JdbcJobExecutionDao$JobExecutionRowMapper.mapRow(JdbcJobExecutionDao.java:401)
        at org.springframework.jdbc.core.RowMapperResultSetExtractor.extractData(RowMapperResultSetExtractor.java:94)
        at org.springframework.jdbc.core.RowMapperResultSetExtractor.extractData(RowMapperResultSetExtractor.java:61)
        at org.springframework.jdbc.core.JdbcTemplate$1.doInPreparedStatement(JdbcTemplate.java:679)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:617)
        at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:669)
        at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:700)
        at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:712)
        at org.springframework.jdbc.core.JdbcTemplate.queryForObject(JdbcTemplate.java:790)
        at org.springframework.batch.core.repository.dao.JdbcJobExecutionDao.getJobExecution(JdbcJobExecutionDao.java:275)
        at org.springframework.batch.core.explore.support.SimpleJobExplorer.getStepExecution(SimpleJobExplorer.java:158)
        at sun.reflect.GeneratedMethodAccessor611.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)`

**Comment by benas** [comment]
I don't see how the number of partitions is related to that. If one of the workers fails, the manager should fail as well (or timeout and fail). Please provide a minimal complete example that reproduces the issue to be able to debug the case. Thank you upfront.
