### ISSUE TITLE
Log messages inside the constructor of scoped bean could be ignored.

### ISSUE THREAD

**Issue by umbum** [spring-projects/spring-batch#4170]
**Bug description**
When the uninitialized scoped bean is passed to slf4j log method, log messages inside the constructor of scoped bean are ignored.

**Environment**
```
org.springframework.boot:spring-boot-starter-batch:2.7.2
org.springframework.batch:spring-batch-core:4.3.6
org.springframework.boot:spring-boot-starter-logging:2.7.2
ch.qos.logback:logback-classic:1.2.11
org.apache.logging.log4j:log4j-to-slf4j:2.17.2
org.slf4j:jul-to-slf4j:1.7.36
```

**Steps to reproduce**
**Minimal Complete Reproducible example**

```java
@Slf4j
@RequiredArgsConstructor
@Configuration
public class SimpleJobConfig {
    private final JobBuilderFactory jobBuilderFactory;
    private final StepBuilderFactory stepBuilderFactory;
    private final JobScopedBeanA jobScopedBeanA;
    private final JobScopedBeanB jobScopedBeanB;

    @Bean
    public Job simpleJob() {
        return jobBuilderFactory.get("simpleJob")
            .start(simpleStep1())
            .build();
    }

    @Bean
    public Step simpleStep1() {
        return stepBuilderFactory.get("simpleStep1")
            .tasklet((contribution, chunkContext) -> {
                log.info(">>>>> This is Step1 {}", jobScopedBeanA);
                log.info(">>>>> This is Step1 {}", jobScopedBeanB.toString());
                return RepeatStatus.FINISHED;
            })
            .build();
    }
}
```
```java
@Slf4j
@JobScope
@Component
@Getter
@ToString
public class JobScopedBeanA {
    private final String fieldA;

    public JobScopedBeanA() {
        this.fieldA = "fieldA";
        log.info("### meta:fieldA {}", fieldA);
    }
}

@Slf4j
@JobScope
@Component
@Getter
@ToString
public class JobScopedBeanB {
    private final String fieldB;

    public JobScopedBeanB() {
        this.fieldB = "fieldB";
        log.info("### meta:fieldB {}", fieldB);
    }
}
```

#### result
```
2022-07-27 16:10:48.643  INFO 12908 --- [  restartedMain] o.s.batch.core.job.SimpleStepHandler     : Executing step: [simpleStep1]
2022-07-27 16:10:48.647  INFO 12908 --- [  restartedMain] c.example.batchlogtest.SimpleJobConfig   : >>>>> This is Step1 JobScopedBeanA(fieldA=fieldA)
2022-07-27 16:10:48.648  INFO 12908 --- [  restartedMain] com.example.batchlogtest.JobScopedBeanB  : ### meta:fieldB fieldB
2022-07-27 16:10:48.648  INFO 12908 --- [  restartedMain] c.example.batchlogtest.SimpleJobConfig   : >>>>> This is Step1 JobScopedBeanB(fieldB=fieldB)
2022-07-27 16:10:48.652  INFO 12908 --- [  restartedMain] o.s.batch.core.step.AbstractStep         : Step: [simpleStep1] executed in 9ms
```

**Expected behavior**
`### meta:fieldA fieldA` have to be printed.

**Comment by fmbenhassine** [comment]
Thank you for opening this issue. I tried to reproduce it with the versions you mentioned (see attached zip), but I get another issue related to Spring Boot dependencies:

```
  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v2.7.2)

2022-10-24 10:51:49.728  INFO 81045 --- [           main] SimpleJobConfig                          : Starting SimpleJobConfig using Java 17 on mbenhassine-a02.vmware.com with PID 81045 (/Users/mbenhassine/Downloads/demo/target/classes started by mbenhassine in /Users/mbenhassine/Downloads/demo)
2022-10-24 10:51:49.731  INFO 81045 --- [           main] SimpleJobConfig                          : No active profile set, falling back to 1 default profile: "default"
2022-10-24 10:51:49.780  WARN 81045 --- [           main] ionWarningsApplicationContextInitializer : 

** WARNING ** : Your ApplicationContext is unlikely to start due to a @ComponentScan of the default package.


2022-10-24 10:51:50.143  WARN 81045 --- [           main] s.c.a.AnnotationConfigApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanDefinitionStoreException: Failed to read candidate component class: URL [jar:file:/Users/mbenhassine/.m2/repository/org/springframework/boot/spring-boot-autoconfigure/2.7.2/spring-boot-autoconfigure-2.7.2.jar!/org/springframework/boot/autoconfigure/r2dbc/ConnectionFactoryConfigurations$PoolConfiguration.class]; nested exception is java.lang.IllegalStateException: Could not evaluate condition on org.springframework.boot.autoconfigure.r2dbc.ConnectionFactoryConfigurations$PoolConfiguration due to io/r2dbc/spi/ValidationDepth not found. Make sure your own configuration does not rely on that class. This can also happen if you are @ComponentScanning a springframework package (e.g. if you put a @ComponentScan in the default package by mistake)
2022-10-24 10:51:50.151  INFO 81045 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2022-10-24 10:51:50.168 ERROR 81045 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanDefinitionStoreException: Failed to read candidate component class: URL [jar:file:/Users/mbenhassine/.m2/repository/org/springframework/boot/spring-boot-autoconfigure/2.7.2/spring-boot-autoconfigure-2.7.2.jar!/org/springframework/boot/autoconfigure/r2dbc/ConnectionFactoryConfigurations$PoolConfiguration.class]; nested exception is java.lang.IllegalStateException: Could not evaluate condition on org.springframework.boot.autoconfigure.r2dbc.ConnectionFactoryConfigurations$PoolConfiguration due to io/r2dbc/spi/ValidationDepth not found. Make sure your own configuration does not rely on that class. This can also happen if you are @ComponentScanning a springframework package (e.g. if you put a @ComponentScan in the default package by mistake)
	at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.scanCandidateComponents(ClassPathScanningCandidateComponentProvider.java:457) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.findCandidateComponents(ClassPathScanningCandidateComponentProvider.java:316) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.context.annotation.ClassPathBeanDefinitionScanner.doScan(ClassPathBeanDefinitionScanner.java:276) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.context.annotation.ComponentScanAnnotationParser.parse(ComponentScanAnnotationParser.java:128) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.context.annotation.ConfigurationClassParser.doProcessConfigurationClass(ConfigurationClassParser.java:296) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.context.annotation.ConfigurationClassParser.processConfigurationClass(ConfigurationClassParser.java:250) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:207) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.context.annotation.ConfigurationClassParser.parse(ConfigurationClassParser.java:175) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:331) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:247) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:311) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:112) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:746) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:564) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734) ~[spring-boot-2.7.2.jar:2.7.2]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408) ~[spring-boot-2.7.2.jar:2.7.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[spring-boot-2.7.2.jar:2.7.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-2.7.2.jar:2.7.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295) ~[spring-boot-2.7.2.jar:2.7.2]
	at SimpleJobConfig.main(SimpleJobConfig.java:20) ~[classes/:na]
Caused by: java.lang.IllegalStateException: Could not evaluate condition on org.springframework.boot.autoconfigure.r2dbc.ConnectionFactoryConfigurations$PoolConfiguration due to io/r2dbc/spi/ValidationDepth not found. Make sure your own configuration does not rely on that class. This can also happen if you are @ComponentScanning a springframework package (e.g. if you put a @ComponentScan in the default package by mistake)
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:54) ~[spring-boot-autoconfigure-2.7.2.jar:2.7.2]
	at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:108) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:88) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.context.annotation.ConditionEvaluator.shouldSkip(ConditionEvaluator.java:71) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.isConditionMatch(ClassPathScanningCandidateComponentProvider.java:512) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.isCandidateComponent(ClassPathScanningCandidateComponentProvider.java:495) ~[spring-context-5.3.22.jar:5.3.22]
	at org.springframework.context.annotation.ClassPathScanningCandidateComponentProvider.scanCandidateComponents(ClassPathScanningCandidateComponentProvider.java:430) ~[spring-context-5.3.22.jar:5.3.22]
	... 19 common frames omitted
Caused by: java.lang.NoClassDefFoundError: io/r2dbc/spi/ValidationDepth
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method) ~[na:na]
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[na:na]
	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2504) ~[na:na]
	at org.springframework.boot.context.properties.bind.JavaBeanBinder$Bean.getSorted(JavaBeanBinder.java:140) ~[spring-boot-2.7.2.jar:2.7.2]
	at org.springframework.boot.context.properties.bind.JavaBeanBinder$Bean.addProperties(JavaBeanBinder.java:132) ~[spring-boot-2.7.2.jar:2.7.2]
	at org.springframework.boot.context.properties.bind.JavaBeanBinder$Bean.<init>(JavaBeanBinder.java:127) ~[spring-boot-2.7.2.jar:2.7.2]
	at org.springframework.boot.context.properties.bind.JavaBeanBinder$Bean.get(JavaBeanBinder.java:226) ~[spring-boot-2.7.2.jar:2.7.2]
	at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:54) ~[spring-boot-2.7.2.jar:2.7.2]
	at org.springframework.boot.context.properties.bind.Binder.lambda$bindDataObject$5(Binder.java:476) ~[spring-boot-2.7.2.jar:2.7.2]
	at org.springframework.boot.context.properties.bind.Binder$Context.withIncreasedDepth(Binder.java:590) ~[spring-boot-2.7.2.jar:2.7.2]
	at org.springframework.boot.context.properties.bind.Binder$Context.withDataObject(Binder.java:576) ~[spring-boot-2.7.2.jar:2.7.2]
	at org.springframework.boot.context.properties.bind.Binder$Context.access$300(Binder.java:537) ~[spring-boot-2.7.2.jar:2.7.2]
	at org.springframework.boot.context.properties.bind.Binder.bindDataObject(Binder.java:474) ~[spring-boot-2.7.2.jar:2.7.2]
	at org.springframework.boot.context.properties.bind.Binder.bindObject(Binder.java:414) ~[spring-boot-2.7.2.jar:2.7.2]
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:343) ~[spring-boot-2.7.2.jar:2.7.2]
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:332) ~[spring-boot-2.7.2.jar:2.7.2]
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:262) ~[spring-boot-2.7.2.jar:2.7.2]
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:223) ~[spring-boot-2.7.2.jar:2.7.2]
	at org.springframework.boot.autoconfigure.r2dbc.ConnectionFactoryConfigurations$PooledConnectionFactoryCondition.getMatchOutcome(ConnectionFactoryConfigurations.java:138) ~[spring-boot-autoconfigure-2.7.2.jar:2.7.2]
	at org.springframework.boot.autoconfigure.condition.SpringBootCondition.matches(SpringBootCondition.java:47) ~[spring-boot-autoconfigure-2.7.2.jar:2.7.2]
	... 25 common frames omitted
Caused by: java.lang.ClassNotFoundException: io.r2dbc.spi.ValidationDepth
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[na:na]
	... 45 common frames omitted
```

Can you please attach a minimal example that I can unzip and run to reproduce the issue?

For the record, the issue does not happen with v5, you can try with the latest snapshots. Here is a sample where the log for both job scoped beans is printed as expected:

```java
package org.springframework.batch.sample;

import javax.sql.DataSource;

import org.springframework.batch.core.Job;
import org.springframework.batch.core.JobParameters;
import org.springframework.batch.core.Step;
import org.springframework.batch.core.configuration.annotation.EnableBatchProcessing;
import org.springframework.batch.core.configuration.annotation.JobBuilderFactory;
import org.springframework.batch.core.configuration.annotation.JobScope;
import org.springframework.batch.core.configuration.annotation.StepBuilderFactory;
import org.springframework.batch.core.job.builder.JobBuilder;
import org.springframework.batch.core.launch.JobLauncher;
import org.springframework.batch.core.repository.JobRepository;
import org.springframework.batch.core.step.builder.StepBuilder;
import org.springframework.batch.repeat.RepeatStatus;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseBuilder;
import org.springframework.jdbc.support.JdbcTransactionManager;
import org.springframework.stereotype.Component;

@Configuration
@EnableBatchProcessing
public class SimpleJobConfig {

    @Bean
    public Job simpleJob(JobRepository jobRepository,
                         JdbcTransactionManager transactionManager,
                         JobScopedBeanA jobScopedBeanA, JobScopedBeanB jobScopedBeanB ) {
        return new JobBuilder("simpleJob", jobRepository)
            .start(simpleStep1(jobRepository, transactionManager, jobScopedBeanA, jobScopedBeanB))
            .build();
    }

    @Bean
    public Step simpleStep1(JobRepository jobRepository,
                            JdbcTransactionManager transactionManager,
                            JobScopedBeanA jobScopedBeanA, JobScopedBeanB jobScopedBeanB ) {
        return new StepBuilder("simpleStep1", jobRepository)
            .tasklet((contribution, chunkContext) -> {
                System.out.println(">>>>> This is Step1 {}" + jobScopedBeanA);
                System.out.println(">>>>> This is Step1 {}" + jobScopedBeanB.toString());
                return RepeatStatus.FINISHED;
            }, transactionManager)
            .build();
    }

    @Bean
    public DataSource dataSource() {
        return new EmbeddedDatabaseBuilder().addScript("/org/springframework/batch/core/schema-drop-hsqldb.sql")
                .addScript("/org/springframework/batch/core/schema-hsqldb.sql").generateUniqueName(true).build();
    }

    @Bean
    public JdbcTransactionManager transactionManager(DataSource dataSource) {
        return new JdbcTransactionManager(dataSource);
    }

    @JobScope
    @Component
    public class JobScopedBeanA {
        private final String fieldA;

        public JobScopedBeanA() {
            this.fieldA = "fieldA";
            System.out.println("### meta:fieldA {}" + fieldA);
        }
    }

    @JobScope
    @Component
    public class JobScopedBeanB {
        private final String fieldB;

        public JobScopedBeanB() {
            this.fieldB = "fieldB";
            System.out.println("### meta:fieldB {}" + fieldB);
        }
    }

    public static void main(String[] args) throws Exception {
        ApplicationContext context = new AnnotationConfigApplicationContext(SimpleJobConfig.class);
        JobLauncher jobLauncher = context.getBean(JobLauncher.class);
        Job job = context.getBean(Job.class);
        jobLauncher.run(job, new JobParameters());
    }
}
```

This prints the following with v5.0 RC1:

```
[main] INFO org.springframework.batch.core.configuration.annotation.BatchRegistrar - Finished Spring Batch infrastrucutre beans configuration in 4 ms.
[main] INFO org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseFactory - Starting embedded database: url='jdbc:hsqldb:mem:085dabc9-b205-4e68-bf4f-3a58486e4f42', username='sa'
[main] INFO org.springframework.batch.core.repository.support.JobRepositoryFactoryBean - No database type set, using meta data indicating: HSQL
[main] INFO org.springframework.batch.core.launch.support.SimpleJobLauncher - No TaskExecutor has been set, defaulting to synchronous executor.
[main] INFO org.springframework.batch.core.launch.support.SimpleJobLauncher - Job: [SimpleJob: [name=simpleJob]] launched with the following parameters: [{}]
[main] INFO org.springframework.batch.core.job.SimpleStepHandler - Executing step: [simpleStep1]
### meta:fieldA {}fieldA
>>>>> This is Step1 {}org.springframework.batch.sample.SimpleJobConfig$JobScopedBeanA@cdc3aae
### meta:fieldB {}fieldB
>>>>> This is Step1 {}org.springframework.batch.sample.SimpleJobConfig$JobScopedBeanB@7ef2d7a6
[main] INFO org.springframework.batch.core.step.AbstractStep - Step: [simpleStep1] executed in 32ms
[main] INFO org.springframework.batch.core.launch.support.SimpleJobLauncher - Job: [SimpleJob: [name=simpleJob]] completed with the following parameters: [{}] and the following status: [COMPLETED] in 50ms
```

**Comment by fmbenhassine** [comment]
I am closing this issue for now. We will re-open it for further investigation if more details are provided.
