### ISSUE TITLE
Occurred NoClassDefFoundError : io/micrometer/observation/docs/DocumentedObservation on 5.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by kazuki43zoo** [spring-projects/spring-batch#4201]
Probably, [latest 5.0.0-SNAPSHOT](https://github.com/spring-projects/spring-batch/commit/8973c8a5b69057e9d4dce45551711e1810d9159b) not published to Spring Snapshot repository yet. Could you publish the latest snapshot version?

```
java.lang.NoClassDefFoundError: io/micrometer/observation/docs/DocumentedObservation
        at org.springframework.batch.core.job.AbstractJob.execute(AbstractJob.java:289)
        at org.springframework.batch.core.launch.support.SimpleJobLauncher$1.run(SimpleJobLauncher.java:147)
        at org.springframework.core.task.SyncTaskExecutor.execute(SyncTaskExecutor.java:50)
```

**Comment by fmbenhassine** [comment]
Thank you for reporting this issue. In fact, the build was broken for some time due to a change in micrometer. New snapshots are now available without this issue.
