### ISSUE TITLE
Conditional Flow for steps does not work 

### ISSUE THREAD

**Issue by vatsla20** [spring-projects/spring-batch#4328]
Condition flow mention in the spring document not working as expected.

**Environment**
spring-boot-starter-parent - 3.0.1
spring.batch.version - 5.0.0

As mentioned here I have used a similar approach to my job (https://docs.spring.io/spring-batch/docs/current/reference/html/step.html#conditionalFlow)

 _public Job exportJob() {
    return new JobBuilder(jobname, jobRepository)
        .incrementer(new RunIdIncrementer())
        .listener(jobListener)
        .start(step1("params"))
            .next(step2())
            .on("COMPLETED").to(step3())
            .from(step2()).on("COMPLETED").to(step4())
        .end()
        .build();
  }_

I want the step4 to be executed on the failure of step2 and step3 on success.
Currently whichever condition in mention in the 'on' statement that works fine but condition mention in 'from' statement is ignored and I get this error. 

_org.springframework.batch.core.JobExecutionException: Flow execution ended unexpectedly
	at org.springframework.batch.core.job.flow.FlowJob.doExecute(FlowJob.java:143) ~[spring-batch-core-5.0.0.jar:5.0.0]
	at org.springframework.batch.core.job.AbstractJob.execute(AbstractJob.java:316) ~[spring-batch-core-5.0.0.jar:5.0.0]
	at org.springframework.batch.core.launch.support.SimpleJobLauncher$1.run(SimpleJobLauncher.java:157) ~[spring-batch-core-5.0.0.jar:5.0.0]
	at org.springframework.core.task.SyncTaskExecutor.execute(SyncTaskExecutor.java:50) ~[spring-core-6.0.3.jar:6.0.3]
	at org.springframework.batch.core.launch.support.SimpleJobLauncher.run(SimpleJobLauncher.java:148) ~[spring-batch-core-5.0.0.jar:5.0.0]
	at org.springframework.batch.core.launch.support.TaskExecutorJobLauncher.run(TaskExecutorJobLauncher.java:70) ~[spring-batch-core-5.0.0.jar:5.0.0]
Caused by: org.springframework.batch.core.job.flow.FlowExecutionException: Ended flow=ExportPipeline at state=ExportPipeline.step2 with exception
	at org.springframework.batch.core.job.flow.support.SimpleFlow.resume(SimpleFlow.java:177) ~[spring-batch-core-5.0.0.jar:5.0.0]
	at org.springframework.batch.core.job.flow.support.SimpleFlow.start(SimpleFlow.java:142) ~[spring-batch-core-5.0.0.jar:5.0.0]
	at org.springframework.batch.core.job.flow.FlowJob.doExecute(FlowJob.java:137) ~[spring-batch-core-5.0.0.jar:5.0.0]_

**Is this an issue with spring batch?
Could I please get a solution for such a conditional scenario for the steps execution? 
 Thanks in advance.**

**Comment by fmbenhassine** [comment]
Thank you for opening this issue. However, we are not sure to reproduce your specific problem by piecing things together from code snippets.

If you would like us to spend some time investigating, please spend some time providing a complete yet minimal example that reproduces the problem. To help you in reporting your issue, we have prepared a project template that you can use as a starting point. Please check the [Issue Reporting Guidelines](https://github.com/spring-projects/spring-batch/blob/main/ISSUE_REPORTING.md) for more details about this.

Thank you for your collaboration.
