### ISSUE TITLE
Can't run job a second time if empty list is passed as parameter the first time (Oracle)

### ISSUE THREAD

**Issue by nyg** [spring-projects/spring-batch#4427]
**Bug description**
When a job has a parameter of type `java.util.List` and the job is run with an empty list and the database is Oracle, it is not possible to run the job a second time.

The exception `java.lang.IllegalArgumentException: value must not be null` will be thrown by `JobParameter` because it is trying to convert null into a List. The null values comes from the fact that empty strings are the same thing as null for Oracle database (the empty string being the serialised empty list).

**Environment**
- Spring Batch 5.0.2
- Java 17
- Oracle database

**Steps to reproduce**
1. Create a job with a parameter of type List
2. Run the job with an empty list as argument
3. Run the job a second time (with any value as argument)

**Expected behavior**
It should be possible to run such a job an infinite number of times.

**Minimal Complete Reproducible example**
https://git.sr.ht/~nyg/example-java-spring-batch-bug

**Comment by weikangchia** [comment]
Hi @nyg , I am facing this issue also and would like to check if you have found any workaround?

**Comment by nyg** [comment]
Hello @weikangchia, the only workaround I found was to prevent null values from being given as parameters to a job...

**Comment by fmbenhassine** [comment]
This seems specific to Oracle, as reported (I tested a couple other databases and the issue does not happen).

I am not an Oracle expert, but is there a way to tell Oracle to keep empty strings as empty strings and not persist them as `null`? I am not sure how Spring Batch can detect that case when deserializing job parameters.

That said, what's the point of using an empty list as a job parameter? Is there a valid use case I am missing?

**Comment by nyg** [comment]
Our use case is that we pass two lists of "internal" and "external" provider names. We then perform different actions on these providers. Sometime one of the two can be empty if it is not wanted in the job result.

**Comment by Swedish-li** [comment]
When I accidentally pass in an empty parameter , now I can only modify the data in BATCH_JOB_EXECUTION_PARAMS   to avoid this error.
I think we need some other ways to solve this problem.

**Comment by ilopezv** [comment]
Same problem here with spring boot 3.5.6 and SCDF 2.11.5 (last opensource version)

When running batch with an empty parameter on it (ex: _CTROL=RE FLIQPROF=30-09-2025 NPROFESI=403391 **NFACAUTO=**_) the batch process runs fine, but later executions fails due to org.springframework.batch.core.JobParameter constructor marked as @NotNull due to empty field (NFACAUTO in the example) was stored as null in BOOT3_BATCH_JOB_EXECUTION_PARAMS.

```
o.s.jdbc.core.StatementCreatorUtils      : Setting SQL statement parameter value: column index 4, parameter value [java.lang.IllegalArgumentException: value must not be null
	at org.springframework.util.Assert.notNull(Assert.java:181)
	at org.springframework.batch.core.JobParameter.<init>(JobParameter.java:52)
	at org.springframework.batch.core.repository.dao.JdbcJobExecutionDao.lambda$getJobParameters$2(JdbcJobExecutionDao.java:463)
	at org.springframework.jdbc.core.JdbcTemplate$RowCallbackHandlerResultSetExtractor.extractData(JdbcTemplate.java:1770)
	at org.springframework.jdbc.core.JdbcTemplate$1.doInPreparedStatement(JdbcTemplate.java:733)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:658)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:723)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:754)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:783)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:799)
	at org.springframework.batch.core.repository.dao.JdbcJobExecutionDao.getJobParameters(JdbcJobExecutionDao.java:468)
	at org.springframework.batch.core.repository.dao.JdbcJobExecutionDao$JobExecutionRowMapper.mapRow(JdbcJobExecutionDao.java:494)
	at org.springframework.batch.core.repository.dao.JdbcJobExecutionDao$JobExecutionRowMapper.mapRow(JdbcJobExecutionDao.java:479)
	at org.springframework.jdbc.core.JdbcTemplate$ResultSetSpliterator.tryAdvance(JdbcTemplate.java:1798)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.FindOps$FindOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.findFirst(Unknown Source)
	at org.springframework.batch.core.repository.dao.JdbcJobExecutionDao.getLastJobExecution(JdbcJobExecutionDao.java:339)
	at org.springframework.batch.core.explore.support.SimpleJobExplorer.getLastJobExecution(SimpleJobExplorer.java:98)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:360)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpo], value class [java.lang.String], SQL type 12
```

Batch process running on SB 2.7.18 are working well because @NotNull restriction on JobParameter was introduced in Spring batch 5.0 and SB 2.7.18 uses Spring batch 4.3.10

**Comment by ilopezv** [comment]
Is strange becase in docs it could be null at BATCH_JOB_EXECUTION_PARAMS
but _org.springframework.batch.core.JobParameter_ don´t honor this restriction neither at doc https://docs.spring.io/spring-batch/reference/schema-appendix.html#metaDataBatchJobParams, neither at code https://github.com/spring-projects/spring-batch/blob/v5.2.4/spring-batch-core/src/main/resources/org/springframework/batch/core/schema-oracle.sql#L30

**Comment by ilopezv** [comment]
Spring Batch does not support null parameters, so it instantiates them as empty Strings. The problem is that Oracle does not support empty Strings, for Oracle they are null. Therefore, when inserting a record, JdbcJobExecutionDao inserts null, poisoning the table and consequence runs fails at JdbcJobExecutionDao.getLastJobExecution

Starting with Oracle 12c, the following can be used: https://oracle-base.com/articles/23/default-on-null-for-insert-and-update-23#for-insert-only

`default on null VALUE` differs from `defaults VALUE` in that it supports the explicit definition of nulls in the insert statement.

As a workaround executing the following ALTER TABLE statement solves the problem:
`ALTER TABLE BATCH_JOB_EXECUTION_PARAMS MODIFY PARAMETER_VALUE VARCHAR2(2500 CHAR) default on null ' ';`
