### ISSUE TITLE
Jackson2ExecutionContextStringSerializer: customization

### ISSUE THREAD

**Issue by rakshitcgupta** [spring-projects/spring-batch#4721]
Need support to add primitive array classes for 

`Caused by: java.lang.IllegalArgumentException: The class with [I and name of [I is not trusted. If you believe this class is safe to deserialize, you can add it to the base set of trusted classes at construction time or provide an explicit mapping using Jackson annotations or a custom ObjectMapper. If the serialization is only done by a trusted source, you can also enable default typing.`

Tried the following but nothing seems to work
        **factory.setSerializer(new Jackson2ExecutionContextStringSerializer("Integer[].class", "int[].class", "[I", "int[]"));**

code below

`@Override
    public JobRepository createJobRepository() throws Exception {
        JobRepositoryFactoryBean factory = new JobRepositoryFactoryBean();
        factory.setDataSource(cdsDataSource);
        factory.setTransactionManager(cdsTransactionManager);
        factory.setIsolationLevelForCreate("ISOLATION_READ_COMMITTED");
        factory.setDatabaseType("ORACLE");
        factory.afterPropertiesSet();
        System.out.println(Class.forName("[I").getName());
        System.out.println(Class.forName("[I").getCanonicalName());
        factory.setSerializer(new Jackson2ExecutionContextStringSerializer("Integer[].class", "int[].class", "[I", "int[]"));
        return factory.getObject();
    }`

**Comment by harshalh10** [comment]
Hi @fmbenhassine, I am also facing the same issue. Could you please help us here?

**Comment by fmbenhassine** [comment]
I would love to help, but please follow the bug report template that we carefully designed to save everyone's time:

- https://github.com/spring-projects/spring-batch/blob/main/.github/ISSUE_TEMPLATE/bug_report.md
- https://github.com/spring-projects/spring-batch/blob/main/ISSUE_REPORTING.md

Which Spring Batch version do you use? Which Jackson version do you use? How can I reproduce your issue?

TIA

**Comment by harshalh10** [comment]
**Bug description**
Migrating Application from Java 1.8 and Spring boot 2.1.2 to Java 11 and 2.7.18

**Environment**
Spring Boot 2.7.18
Java 11
Spring Batch 4.3.10
Jackson 2.15.3
Oracle SQL

**Steps to reproduce**

1. Configure and run a job with Java 1.8 and Spring boot 2.1.2 
2. call `private Set<JobExecution> findNotCompletedJobsInstances(String jobName) {
        return customJobExplorer.getJobExecutionIds(jobName).stream()
                .map(jobExplorer::getJobExecution)
                .filter(jobExecution -> jobExecution != null && notCompletedJobExecution(jobExecution))
                .collect(Collectors.toSet());
    }
`
`
@Component
@RequiredArgsConstructor
public class CustomJobExplorer {

    private final JdbcTemplate jdbcTemplate;

    public List<String> getJobNamesForRunId(Long runId) {
        final String sqlQuery = String.format("SELECT i.job_name FROM batch_job_instance i, batch_job_execution e WHERE i.job_instance_id = e.job_instance_id and i.job_name like '%%RunId-%s'", runId);
        return jdbcTemplate.queryForList(sqlQuery, String.class);
    }

    public List<Long> getJobExecutionIds(String jobName) {
        final String sqlQuery = String.format("SELECT e.job_execution_id FROM batch_job_instance i, batch_job_execution e WHERE i.job_instance_id = e.job_instance_id and i.job_name = '%s'", jobName);
        return jdbcTemplate.queryForList(sqlQuery, Long.class);
    }
}
`
3. Migrate to Java 11 and Spring boot 2.7.18
4. call `private Set<JobExecution> findNotCompletedJobsInstances(String jobName) {
        return customJobExplorer.getJobExecutionIds(jobName).stream()
                .map(jobExplorer::getJobExecution)
                .filter(jobExecution -> jobExecution != null && notCompletedJobExecution(jobExecution))
                .collect(Collectors.toSet());
    }
`
`
@Component
@RequiredArgsConstructor
public class CustomJobExplorer {

    private final JdbcTemplate jdbcTemplate;

    public List<String> getJobNamesForRunId(Long runId) {
        final String sqlQuery = String.format("SELECT i.job_name FROM batch_job_instance i, batch_job_execution e WHERE i.job_instance_id = e.job_instance_id and i.job_name like '%%RunId-%s'", runId);
        return jdbcTemplate.queryForList(sqlQuery, String.class);
    }

    public List<Long> getJobExecutionIds(String jobName) {
        final String sqlQuery = String.format("SELECT e.job_execution_id FROM batch_job_instance i, batch_job_execution e WHERE i.job_instance_id = e.job_instance_id and i.job_name = '%s'", jobName);
        return jdbcTemplate.queryForList(sqlQuery, Long.class);
    }
}
`
5. Expect a stacktrace
`
Caused by: java.lang.IllegalArgumentException: Unable to deserialize the execution context
	at org.springframework.batch.core.repository.dao.JdbcExecutionContextDao$ExecutionContextRowMapper.mapRow(JdbcExecutionContextDao.\
java:327) ~[spring-batch-core-4.3.10.jar!/:4.3.10]
	at org.springframework.batch.core.repository.dao.JdbcExecutionContextDao$ExecutionContextRowMapper.mapRow(JdbcExecutionContextDao.\
java:312) ~[spring-batch-core-4.3.10.jar!/:4.3.10]
	at org.springframework.jdbc.core.RowMapperResultSetExtractor.extractData(RowMapperResultSetExtractor.java:94) ~[spring-jdbc-5.3.31\
.jar!/:5.3.31]
	at org.springframework.jdbc.core.RowMapperResultSetExtractor.extractData(RowMapperResultSetExtractor.java:61) ~[spring-jdbc-5.3.31\
.jar!/:5.3.31]
`
SKIPPED trace
`
Caused by: com.fasterxml.jackson.databind.JsonMappingException: The class with [I and name of [I is not trusted. If you believe thi\
s class is safe to deserialize, you can add it to the base set of trusted classes at construction time or provide an explicit mappi\
ng using Jackson annotations or a custom ObjectMapper. If the serialization is only done by a trusted source, you can also enable d\
efault typing. (through reference chain: java.util.HashMap["columnTypes"])
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:241) ~[spring-aop-5.3.31.jar!/:5.3.31]
	at com.sun.proxy.$Proxy83.getJobExecution(Unknown Source) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
	at com.reporting.batch.feed.FeedJobService.findNotCompletedJobsInstances(FeedJobService.java:55) ~[classes!/:43.0.15]
	at com.reporting.batch.feed.FeedJobService.lambda$cleanupRunningJobs$0(FeedJobService.java:33) ~[classes!/:43.0.15]
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271) ~[?:?]
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497) ~[?:?]
	at com.reporting.batch.feed.FeedJobService.cleanupRunningJobs(FeedJobService.java:34) ~[classes!/:43.0.15]
	at com.reporting.batch.feed.paragon.ParagonFeed.run(ParagonFeed.java:60) ~[classes!/:43.0.15]
	at com.reporting.batch.feed.JavadirectorRunner.run(JavadirectorRunner.java:26) ~[classes!/:43.0.15]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:765) ~[spring-boot-2.7.18.jar!/:2.7.18]
`


**Expected behavior**
No exception occurs in deserialization

**Tried following way:**

Override `getJobRepository()` and `getJobExplorer()`

`@Configuration
@EnableTransactionManagement
public class ParagonFeedConfig extends DefaultBatchConfigurer {


    @Autowired
    private DataSource cdsDataSource;


    @Autowired
    private PlatformTransactionManager cdsTransactionManager;


    @Autowired
    private EnhancingListenerService enhancingListenerService;


    @Bean
    public ContextEnhancingListener contextEnhancingListener() {
        return new ContextEnhancingListener(cdsDataSource, enhancingListenerService);
    }

    @Bean
    public TasksCompletionMonitor stepTasksCompletionMonitor() {
        return new TasksCompletionMonitor();
    }

    @Bean
    public TasksCompletionMonitor jobTasksCompletionMonitor() {
        return new TasksCompletionMonitor();
    }


    public JobRepository createJobRepository() throws Exception {
        JobRepositoryFactoryBean factory = new JobRepositoryFactoryBean();
        factory.setDataSource(cdsDataSource);
        factory.setTransactionManager(cdsTransactionManager);
        factory.setIsolationLevelForCreate("ISOLATION_READ_COMMITTED");
        factory.setDatabaseType("ORACLE");
        factory.afterPropertiesSet();
        return factory.getObject();
    }

    @Override
    public JobRepository getJobRepository() {
        JobRepositoryFactoryBean factory = new JobRepositoryFactoryBean();
        factory.setDataSource(cdsDataSource);
        factory.setTransactionManager(cdsTransactionManager);
        factory.setIsolationLevelForCreate("ISOLATION_READ_COMMITTED");
        factory.setDatabaseType("ORACLE");
        factory.setSerializer(createCustomSerializer());
        try {
            factory.afterPropertiesSet();
            return factory.getObject();
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    @Override
    public JobExplorer getJobExplorer() {
        JobExplorerFactoryBean factoryBean = new JobExplorerFactoryBean();
        factoryBean.setSerializer(createCustomSerializer());
        factoryBean.setDataSource(cdsDataSource);
        try {
            factoryBean.afterPropertiesSet();
            return factoryBean.getObject();
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    private ExecutionContextSerializer createCustomSerializer() {
        Jackson2ExecutionContextStringSerializer serializer = new Jackson2ExecutionContextStringSerializer("[I", "int[]");
        return serializer;
    }

}
`
