### ISSUE TITLE
JobLauncherTestUtils.launchStep() don't find step of a Flow with split [BATCH-2826]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-batch#788]
**[atokle](https://jira.spring.io/secure/ViewProfile.jspa?name=atokle)** opened **[BATCH-2826](https://jira.spring.io/browse/BATCH-2826?redirect=false)** and commented

I use spring-boot-starter-batch 2.1.5 that uses spring-batch 4.1.2

I try to run two steps in parallell, and that works fine. I can also start the JobLauncherTestUtils.launchJob(), and see that both steps is launched and runs.

But if I try to test a single step with JobLauncherTestUtils.launchStep("step1"), it throws an exception 

```java
java.lang.IllegalStateException: No Step found with name: [step1]
 at org.springframework.batch.test.JobLauncherTestUtils.launchStep(JobLauncherTestUtils.java:239)
 at org.springframework.batch.test.JobLauncherTestUtils.launchStep(JobLauncherTestUtils.java:189) 
```

 

The batch is configured with Java Config like this. (anymonized)

```java
@Configuration
@ComponentScan(basePackageClasses = {UpdateStatusBatchConfig.class})
public class UpdateStatusBatchConfig {
    private final JobBuilderFactory jobBuilderFactory;
    private final StepBuilderFactory stepBuilderFactory;
    private final MyDomainsstatusProcessor MyDomainsstatusProcessor;
    private final MyDomainstatusWriter MyDomainstatusWriter;
    private DataSource dataSource;    @Autowired
    public UpdateStatusBatchConfig(JobBuilderFactory jobBuilderFactory,
                                             StepBuilderFactory stepBuilderFactory,
                                             @Qualifier("mydb.datasource") DataSource dataSource,
                                             MyDomainsstatusProcessor MyDomainsstatusProcessor,
                                             MyDomainstatusWriter MyDomainstatusWriter) {
        this.jobBuilderFactory = jobBuilderFactory;
        this.stepBuilderFactory = stepBuilderFactory;
        this.dataSource = dataSource;
        this.MyDomainsstatusProcessor = MyDomainsstatusProcessor;
        this.MyDomainstatusWriter = MyDomainstatusWriter;
    }    

    @Bean("splitFlow")
    Flow splitFlow(
            @Qualifier("step2") Step step2,
            @Qualifier("step1") Step step1) {
        return new FlowBuilder<Flow>("splitFlow")
                .start(new FlowBuilder<Flow>("hentOgOppdaterFkOgYskStatuserFlow").from(step2).build())
                .split(new SimpleAsyncTaskExecutor())
                .add(new FlowBuilder<Flow>("hentOgOppdaterAdrStatuserFlow").from(step1).build())
                .build();
    }    

    @Bean
    public Job job1(
            @Qualifier("splitFlow") Flow splitFlow ) {
        return jobBuilderFactory.get("job1")
                .incrementer(new RunIdIncrementer())
                .start(splitFlow)
                .end()
                .build();
    }    

    @Bean("step2")
    public Step step2(
            @Autowired MyDomainsMapper MyDomainsMapper) throws IOException {
        return stepBuilderFactory.get("step2")
                .<MyDomain, MyDomainsStatus> chunk(1)
                .faultTolerant()
                .reader(MyDomain2Reader(MyDomainsMapper))
                .processor(MyDomainsstatusProcessor)
                .writer(MyDomainstatusWriter)
                .build();
    }    

    @Bean("step1")
    public Step step1(
            @Autowired MyDomainsMapper MyDomainsMapper) throws IOException {
        return stepBuilderFactory.get("step1")
                .<MyDomain, MyDomainsStatus> chunk(1)
                .faultTolerant()
                .reader(MyDomain1Reader(MyDomainsMapper))
                .processor(MyDomainsstatusProcessor)
                .writer(MyDomainstatusWriter)
                .build();
    }    

    @Bean("MyDomain1Reader")
    public JdbcCursorItemReader<MyDomain> MyDomain1Reader(@Autowired MyDomainsMapper MyDomainsMapper) throws IOException {
        return new JdbcCursorItemReaderBuilder<MyDomain>()
                .name("domain1ItemReader")
                .dataSource(dataSource)
                .rowMapper(MyDomainsMapper)
                .sql(new String(copyToByteArray(new ClassPathResource("MyDomain1.sql").getInputStream()), Charset.forName("UTF-8")))
                .build();
    }    

    @Bean("MyDomain2Reader")
    public JdbcCursorItemReader<MyDomain> MyDomain2Reader(@Autowired MyDomainsMapper MyDomainsMapper) throws IOException {
        return new JdbcCursorItemReaderBuilder<MyDomain>()
                .name("domain2ItemReader")
                .dataSource(dataSource)
                .rowMapper(MyDomainsMapper)
                .sql(new String(copyToByteArray(new ClassPathResource("MyDomain2.sql").getInputStream()), Charset.forName("UTF-8")))
                .build();
    }
}
```

If I stop the test in the debugger at the line JobLauncherTestUtils.launchStep("step1") and inspects 

jobLauncherTestUtils.job.flow.startState.flows I can see the two subFlows but startState is null, and stateMap is empty. 

If I from debugger runs 

((SimpleFlow) ((ArrayList) ((SplitState)((SimpleFlow)((FlowJob)jobLauncherTestUtils.job).flow).startState).flows).get(0)).afterPropertiesSet();
((SimpleFlow) ((ArrayList) ((SplitState)((SimpleFlow)((FlowJob)jobLauncherTestUtils.job).flow).startState).flows).get(1)).afterPropertiesSet();

I can see that the two fields is initialized, and jobLauncherTestUtils will then find and run the step correctly.

---

**Affects:** 4.1.2

**Comment by mminella** [comment]
The issue here is that since the sub flows (`hentOgOppdaterFkOgYskStatuserFlow` and `hentOgOppdaterAdrStatuserFlow`) are not exposed to the container, the responsibility of calling the lifecycle methods (`IntializerBean#afterPropertiesSet()` in this case) is up to you.  In the process of digging into this issue, we realized that our docs are missing the call as well.  These have been updated to defer to the container to handle the lifecycle of the bean (d41cd45f901c2699f3d0f5e6b7fe1931787259ff).
