### ISSUE TITLE
org.springframework.batch.core.JobParameter.toString may return null [BATCH-2772]

### ISSUE THREAD

**Issue by spring-projects-issues** [spring-projects/spring-batch#834]
**[Dmitry Smeliansky](https://jira.spring.io/secure/ViewProfile.jspa?name=dmitrysm2000)** opened **[BATCH-2772](https://jira.spring.io/browse/BATCH-2772?redirect=false)** and commented

```java
public String toString() { public String toString() { return parameter == null ? null : (parameterType == ParameterType.DATE ? "" + ((Date) parameter).getTime() : parameter.toString()); }
```

This behavior causes NPE in the JopParameters.toProperties method

```java
java.lang.NullPointerException at java.util.Hashtable.put(Hashtable.java:459) at org.springframework.batch.core.JobParameters.toProperties(JobParameters.java:219) 
```

---

**Affects:** 3.0.7

**Comment by benas** [comment]
Fixed in #3864 .
