### ISSUE TITLE
Check field is not synthetic in BeanWrapperFieldExtractor [BATCH-2683]

### ISSUE THREAD

**Issue by spring-issuemaster** [spring-projects/spring-batch#925]
**[Cédric Sarre](https://jira.spring.io/secure/ViewProfile.jspa?name=cedric.sarre)** opened **[BATCH-2683](https://jira.spring.io/browse/BATCH-2683?redirect=false)** and commented

Hello!

I have defined a class extended BeanWrapperFieldExtractor class.
I am overriding the extract method with the following code:

```java
@Override
public Object[] extract(T item) {
	return Arrays.asList(super.extract(item))
		.stream()
		.map(value -> value == null ? "NULL" : value.toString().toUpperCase())
		.map(value -> "\"" + value + "\"")
		.toArray();
}
```

I am using Jacoco plugin to have my code coverage but during build of my application, I have the following error:

```
Caused by: org.springframework.beans.NotReadablePropertyException: Invalid property '$jacocoData' of bean class [com.xx.xx.xx.xx.CdCsv]: Bean property '$jacocoData' is not readable or has an invalid getter method: Does the return type of the getter match the parameter type of the setter?
	at org.springframework.beans.AbstractNestablePropertyAccessor.getPropertyValue(AbstractNestablePropertyAccessor.java:619)
	at org.springframework.beans.AbstractNestablePropertyAccessor.getPropertyValue(AbstractNestablePropertyAccessor.java:609)
	at xx.xx.xx.xx.common.ConfigurableBeanWrapperFieldExtractor.extract(ConfigurableBeanWrapperFieldExtractor.java:33)
	at org.springframework.batch.item.file.transform.ExtractorLineAggregator.aggregate(ExtractorLineAggregator.java:54)
	at org.springframework.batch.item.file.FlatFileItemWriter.write(FlatFileItemWriter.java:270)
	at org.springframework.batch.core.step.item.SimpleChunkProcessor.writeItems(SimpleChunkProcessor.java:175)
	at org.springframework.batch.core.step.item.SimpleChunkProcessor.doWrite(SimpleChunkProcessor.java:151)
	at org.springframework.batch.core.step.item.FaultTolerantChunkProcessor$3.doWithRetry(FaultTolerantChunkProcessor.java:330)
	at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:287)
	... 61 common frames omitted
```

In order to collect execution data JaCoCo instruments the classes under test which adds two members to the classes: a private static field $jacocoData and a private static method $jacocoInit(). Both members are marked as synthetic (as explained in http://www.jacoco.org/jacoco/trunk/doc/faq.html)

The method extract of BeanWrapperFieldExtractor doesn't manage the check of synthetic members. A fix could be to add a check like:

```java
public Object[] extract(T item) {
	List<Object> values = new ArrayList<Object>();

	BeanWrapper bw = new BeanWrapperImpl(item);
	for (String propertyName : this.names) {
		Field field = ReflectionUtils.findField(item.getClass(), propertyName);
		if (field == null || !field.isSynthetic()) {
			values.add(bw.getPropertyValue(propertyName));
		}
	}
	return values.toArray();
}
```

---

**Affects:** 4.0.0

**Issue Links:**
- [BATCH-2446](https://jira.spring.io/browse/BATCH-2446) IllegalAccessException when running JaCoCo

1 votes, 2 watchers

**Comment by benas** [comment]
According to the stacktrace, the error happen in `xx.xx.xx.xx.common.ConfigurableBeanWrapperFieldExtractor` which is not a Spring Batch class. This class is probalby trying to get all fields without excluding those added by JaCoCo, hence the error.

The `BeanWrapperFieldExtractor` provided by Spring Batch will [iterate only](https://github.com/spring-projects/spring-batch/blob/d8fc58338d3b059b67b5f777adc132d2564d7402/spring-batch-infrastructure/src/main/java/org/springframework/batch/item/file/transform/BeanWrapperFieldExtractor.java#L56) over the fields set using `setNames`.  For example:

```java
BeanWrapperFieldExtractor<Person> fieldExtractor = new BeanWrapperFieldExtractor<>();
fieldExtractor.setNames(new String[]{"id", "name"});
```

the field extractor will only try to call the getters of `id` and `name` fields. So unless "$jacocoData" is added manually to the list of field names, I don't see how it is possible to have the error with the built-in `BeanWrapperFieldExtractor`.

To confirm things, I created a [repo](https://github.com/benas/spring-batch-sandbox/tree/master/gh925) to show that even with a JaCoCo instrumented class (having the `$jacocoData` field in it at runtime), no exception is thrown (tested from both my IDE when running tests with JaCoCo coverage and from the command line). Tested with JaCoCo 0.8.5 and Spring Batch 4.0.0.RELEASE (as reported here) and with the latest 4.2.1.RELEASE as well.

So please share the code of `xx.xx.xx.xx.common.ConfigurableBeanWrapperFieldExtractor` or provide a minimal complete example that reproduces the issue.
